/* AI Art Daily — article dataset */
window.AIAD = {
  tabs: [
    { id: 'games',    label: '게임 제작 속 AI',    desc: '게임 아트 리소스 제작에 사용되는 AI 관련 뉴스들을 매일 업데이트합니다.' },
    { id: 'industry', label: 'AI 도입 뉴스',       desc: '게임 스튜디오들의 AI 도입과 관련된 뉴스들을 매일 업데이트합니다.' },
    { id: 'art',      label: '아트 전반 AI 뉴스',  desc: '게임 제작과 무관하게 모든 아트 관련 AI 뉴스들을 매일 업데이트합니다.' },
    { id: 'repos',    label: '오픈소스 업데이트',  desc: 'Github 오픈소스 프로젝트들의 업데이트 뉴스들을 매일 업데이트합니다. 오픈소스 프로젝트 목록은 \'유용한 소스\' 탭에서 확인해주세요.' },
  ],
 
  /*
   * Each article shape:
   * {
   *   id:          'unique-slug',          // any unique string
   *   tab:         'games',                // must match a tab id above
   *   headline:    '한국어 제목',
   *   summary:     '한 줄 요약',
   *   body:        '<p>본문 첫 문단</p><p>두 번째 문단…</p>',  // 카드 클릭 시 모달 본문 (HTML 허용)
   *   source:      '출처',
   *   publishedAt: '2026.04.25',           // 'YYYY.MM.DD' 형식, 사이트 업로드 날짜 (정렬·날짜 헤더에 사용; 화면에는 그대로 표시됨)
   *   hue:         30,                     // 0–360, 그라디언트 썸네일 색상
   *   image:       'assets/news/x.jpg',    // optional — 있으면 그라디언트 대신 이미지 사용
   *   url:         'https://...',          // 원문 링크
   *   urls: [                              // optional — 추가 관련 링크
   *     { label: '관련 보도', href: 'https://...' },
   *     { label: '공식 발표', href: 'https://...' },
   *   ],
   * }
   */
  articles: [
    /* ---- games ---- */
        {
            id:          'games-3868e758-2026-05',
            tab:         'games',
            headline:    '개발자가 가우시안 스플래팅으로 브라우저에서 돌아가는 FPS 게임 제작',
            summary:     '개발자 이아코프 숨이긴이 실제 폐건물 스캔 데이터로 브라우저 FPS 게임을 만들었어요.',
            body:        '<p>개발자 이아코프 숨이긴이 가우시안 스플래팅 기술을 활용해 실제 폐건물 스캔 데이터를 기반으로 브라우저에서 바로 즐길 수 있는 FPS 게임을 완성했어요. PlayCanvas 엔진 위에서 구동되는 이 게임은 별도 설치 없이 웹 브라우저만 있으면 포토리얼리스틱한 폐허 공간을 배경으로 실시간 게임플레이를 경험할 수 있어요. 가우시안 스플래팅 기술을 실제 게임플레이에 적용한 사례가 극히 드물었던 만큼, 개발자 커뮤니티에서 큰 화제가 되고 있어요.</p><p>가우시안 스플래팅은 2D 이미지나 영상을 머신러닝으로 분석해 포토리얼리스틱한 3D 환경으로 변환하는 기술이에요. 기존 게임 제작에서는 폴리곤 모델링과 텍스처 페인팅 같은 복잡한 과정이 필수였지만, 이 방식은 현실 공간을 촬영한 데이터만으로도 즉각 게임 레벨로 만들 수 있어요. 전통적인 3D 모델링 파이프라인 없이도 실제 공간을 그대로 게임에 옮길 수 있다는 점에서, 인디 개발자나 소규모 스튜디오에서 활용 가능성이 특히 높아 보여요. 게임 아트 제작 비용과 시간을 대폭 줄이면서도 현실감 넘치는 레벨을 구현할 수 있어, 향후 게임 아트 파이프라인에 새로운 방향을 제시한 사례로 주목받고 있어요.</p><p>원문: <a href="https://80.lv/articles/developer-builds-browser-based-fps-game-using-gaussian-splats">80 Level</a></p>',
            source:      '80 Level',
            publishedAt: '2026.05.01',
            hue:         25,
            image:       'https://cdn.80.lv/api/upload/meta/48059/images/69f331f64d1fd/contain_1200x630.jpg',
            url:         'https://80.lv/articles/developer-builds-browser-based-fps-game-using-gaussian-splats',
            urls: [
                { label: '플레이', href: 'https://playcanvas.com' },
            ],
        },
        {
            id:          'games-3a307ec5-2026-05',
            tab:         'games',
            headline:    'Anthropic, 블렌더에 Claude 커넥터 출시 및 공식 후원사 참여',
            summary:     'Anthropic이 Blender 개발 재단의 공식 후원사로 합류하며 Claude AI 커넥터를 함께 출시했어요.',
            body:        '<p>Anthropic이 Blender 개발 재단의 공식 Corporate Patron으로 합류하면서, Blender에서 Claude AI를 자연어로 제어할 수 있는 MCP 기반 커넥터를 함께 공개했어요. 이번 후원금은 Blender Python API를 비롯한 핵심 기능의 유지·개선에 집중적으로 쓰일 예정이며, Blender의 오픈소스 원칙과 재단의 기획·검토 권한은 변함없이 유지돼요. 오픈소스 생태계에 대형 AI 기업이 공식 후원자로 참여하는 사례가 늘고 있는 가운데, Anthropic의 합류는 크리에이티브 소프트웨어 분야에서 AI 도입이 본격화되고 있음을 보여줘요.</p><p>공개된 Claude 커넥터는 자연어로 Blender Python API와 대화할 수 있는 인터페이스를 제공해요. 씬 분석·디버깅, 스크립트 자동 생성, 오브젝트 일괄 수정, Blender 인터페이스에 새 도구 추가 등의 작업을 AI에게 맡길 수 있어요. 커넥터는 Model Context Protocol(MCP) 오픈 표준을 기반으로 구축돼 Claude 외의 대형 언어 모델과도 연동 가능하도록 설계됐고, Blender 5.1 버전부터 공식 지원돼요. Anthropic은 이와 함께 Adobe Creative Cloud, Ableton, Autodesk Fusion, SketchUp, Resolume 등 다양한 크리에이티브 도구와의 커넥터도 함께 발표하며, 창작 산업 전반으로 AI 통합을 적극 확장하고 있어요.</p><p>원문: <a href="https://digitalproduction.com/2026/04/30/anthropic-funds-blender-ships-claude-connector/">Digital Production</a></p>',
            source:      'Digital Production',
            publishedAt: '2026.05.01',
            hue:         220,
            image:       'https://digitalproduction.com/wp-content/uploads/2026/04/lzmwszbzu5w-00-00-13-18-claude-now-connects-to-blender.png',
            url:         'https://digitalproduction.com/2026/04/30/anthropic-funds-blender-ships-claude-connector/',
            urls: [
                { label: '커넥터 정보', href: 'https://github.com/anthropics/claude-code' },
            ],
        },
        {
            id:          'games-6263b2f9-2026-04',
            tab:         'games',
            headline:    'Anthropic, Blender 공식 후원사 합류 — Claude-Blender MCP 서버도 공개',
            summary:     'Anthropic이 연 24만 유로 규모로 Blender Development Fund의 Corporate Patron에 합류했어요.',
            body:        '<p>AI 기업 Anthropic이 Blender Development Fund의 Corporate Patron으로 합류해 연간 24만 유로(약 3억 6천만 원)를 지원하기로 했어요. 이 소식은 커뮤니티 일부에서 생성형 AI 기업의 개입을 우려하는 반응을 불러일으켰어요. 이에 대해 Blender CEO 프란체스코 시디는 이 지원은 Blender 소프트웨어 발전을 위한 것이며 AI 점령이 아니라고 못 박았어요. Blender 재단 정책상 후원 참여는 후원자의 미션이나 전략에 대한 지지를 의미하지 않으며, \'no strings attached\' 원칙이 적용돼요.</p><p>Anthropic 후원 발표와 함께 Blender Lab은 Claude AI 모델을 Blender에 연결하는 MCP 서버도 공개했어요. 이를 통해 아티스트들은 자연어로 Claude에게 3D 씬 디버깅, 오브젝트 일괄 변경 같은 작업을 맡길 수 있게 됐어요. 지난 1년간 Arrowhead Game Studios, Netflix, Epic MegaGrant 등 주요 스폰서를 유치해 온 Blender가 이번에 생성형 AI 기업과도 손을 잡으면서, 3D 아트 파이프라인에서 AI 어시스턴트 활용 가능성이 한층 확장됐어요.</p><p>원문: <a href="https://80.lv/articles/blender-ceo-on-anthropic-funding-this-is-not-ai-takeover">80 Level</a></p>',
            source:      '80 Level',
            publishedAt: '2026.04.30',
            hue:         200,
            image:       'https://cdn.80.lv/api/upload/meta/48035/images/69f1d7bc75b57/contain_1200x630.jpg',
            url:         'https://80.lv/articles/blender-ceo-on-anthropic-funding-this-is-not-ai-takeover',
            urls: [
                { label: '관련 보도', href: 'https://www.cgchannel.com/2026/04/ai-developer-anthropic-becomes-blenders-latest-corporate-patron/' },
            ],
        },
        {
            id:          'games-724981f7-2026-04',
            tab:         'games',
            headline:    'Autodesk Flow Studio, AI 리깅과 뉴럴 레이어로 애니메이션 제작 혁신',
            summary:     'Autodesk가 Flow Studio에 AI 리깅과 뉴럴 레이어를 추가해 캐릭터 애니메이션 제작 시간을 크게 단축했어요.',
            body:        '<p>Autodesk가 AI 시네마 플랫폼 Flow Studio에 AI 리깅과 뉴럴 레이어 두 가지 신기능을 추가했어요. AI 리깅은 캐릭터 모델링 이후 가장 시간이 많이 걸리는 단계인 리깅 작업을 자동화해줘요. 기존에는 숙련된 아티스트도 며칠씩 걸리던 작업을 대폭 단축할 수 있고, 영상 파일을 기반으로 캐릭터 모션을 구동하는 것도 가능해졌어요. 완성된 에셋은 Maya, Blender, 언리얼 엔진으로 내보내기가 그대로 지원돼서 기존 파이프라인과도 자연스럽게 연동돼요.</p><p>뉴럴 레이어는 렌더링의 기술적 장벽을 낮추는 기능으로, 라이팅·머티리얼·시뮬레이션·컴포지팅 같은 고급 요소들을 복잡한 수동 설정 없이 고품질로 뽑아낼 수 있게 해줘요. 두 기능이 합쳐지면 아이디어에서 애니메이션 완성 샷까지 하나의 플랫폼 안에서 처리할 수 있어요. 소규모 인디 팀이나 애니메이션 입문자들이 기술적 준비 단계에 막히지 않고 실제 크리에이티브 작업에 더 빨리 집중할 수 있다는 점이 핵심 장점이에요. 다만 복잡하거나 스타일화된 애니메이션은 여전히 아티스트의 섬세한 손길이 필요하다는 점은 변하지 않아요.</p><p>원문: <a href="https://www.creativebloq.com/art/animation/how-autodesks-new-ai-tool-gets-us-closer-to-just-press-animate">Creative Bloq</a></p>',
            source:      'Creative Bloq',
            publishedAt: '2026.04.29',
            hue:         210,
            image:       'https://cdn.mos.cms.futurecdn.net/WsiyrmsCoiKRDvhiY5Bgu3-1600-80.jpg',
            url:         'https://www.creativebloq.com/art/animation/how-autodesks-new-ai-tool-gets-us-closer-to-just-press-animate',
            urls: [
                { label: '공식 발표', href: 'https://adsknews.autodesk.com/en/news/autodesk-flow-studio-launches-wonder-3d-gen-ai-model-to-help-creators-make-3d-characters-and-objects-faster-and-easier/' },
            ],
        },
        {
            id:          'games-e13fb92a-2026-04',
            tab:         'games',
            headline:    'Reallusion, Headshot 3.0 출시 — 사진 한 장으로 게임용 3D 캐릭터 생성',
            summary:     'Reallusion이 사진 한 장으로 정밀한 3D 캐릭터를 생성하는 Headshot 3.0을 출시했어요.',
            body:        '<p>Reallusion이 Character Creator 5용 AI 플러그인 Headshot의 최신 버전 3.0을 출시했어요. 새 버전은 실제 배우 사진 한 장으로 더욱 정밀한 3D 헤드를 생성하는 새 AI 모델을 탑재했어요. 다양한 연령대와 민족에 걸쳐 더 정확한 결과물을 제공하는 자체 개발 모델로, Refine Face 기능으로 눈꺼풀이나 팔자주름 같은 세부 부위를 가이드 커브로 조정할 수 있어요. 58가지 프리셋 페이셜 모프도 추가돼 슬라이더 하나로 표정 세부 표현을 제어할 수 있어요.</p><p>이번 업데이트에서 가장 눈에 띄는 점은 전신 캐릭터 생성 기능의 추가예요. 이전 버전은 머리만 생성하고 몸통은 프리셋에서 골랐지만, 이제 참고 사진 한 장으로 체형까지 자동 생성돼요. 텍스처 편집에서도 베이크된 라이팅을 제거하는 DeLight 기능과 노멀 맵 세부 제어가 추가됐어요. 영구 라이선스 가격은 199달러로, Character Creator 5와 함께 사용할 수 있어요. 게임이나 VFX에서 실제 배우의 디지털 더블을 빠르게 제작해야 하는 팀에게 캐릭터 아트 파이프라인 효율을 크게 높여줄 업데이트예요.</p><p>원문: <a href="https://www.cgchannel.com/2026/04/reallusion-releases-headshot-3-0/">CG Channel</a></p>',
            source:      'CG Channel',
            publishedAt: '2026.04.29',
            hue:         30,
            image:       'https://www.cgchannel.com/wp-content/uploads/2026/04/260428_Headshot3_NewAIModel.jpg',
            url:         'https://www.cgchannel.com/2026/04/reallusion-releases-headshot-3-0/',
            urls: [
                { label: '공식 발표', href: 'https://magazine.reallusion.com/2026/04/27/reallusion-redefines-digital-double-creation-with-the-launch-of-headshot-3-for-character-creator-5/' },
                { label: '새 기능 보기', href: 'https://manual.reallusion.com/Headshot_Plugin/ENU/3.0/02-Headshot/Whats-New-in-Headshot-3.htm' },
            ],
        },
        {
            id:          'games-5cd5bf09-2026-04',
            tab:         'games',
            headline:    'Anthropic, Blender 개발 기금에 코퍼릿 패트론으로 합류 — 오픈소스 3D 생태계 강화',
            summary:     'Claude AI 개발사 Anthropic이 Blender 재단의 코퍼릿 패트론으로 합류해 오픈소스 3D 개발을 지원해요.',
            body:        '<p>Claude AI를 개발한 Anthropic이 Blender 재단의 개발 기금에 코퍼릿 패트론 등급 기부자로 합류했어요. Blender 개발 기금은 재단이 풀타임 개발자를 고용하고 핵심 기능·성능·장기 인프라 작업을 이어갈 수 있는 주요 재원이에요. Anthropic의 지원금은 Blender Python API 등 핵심 기반 기술 개발에 집중 투입될 예정이라고 재단 측이 밝혔어요. Blender 재단 CEO Francesco Siddi는 \'불확실한 시대에 Anthropic의 지원 덕분에 Blender 팀이 독립적으로 아티스트를 위한 도구 개발에 집중할 수 있게 됐다\'고 전했어요.</p><p>Blender는 최근 A24의 Backrooms 영화 컨셉 아트 제작에 활용되는 등, 게임 개발·VFX·리얼타임 콘텐츠 제작에 걸쳐 오픈소스 대안으로 점점 더 많이 쓰이고 있어요. Anthropic은 특정 기능 로드맵보다는 재정 지원 자체에 초점을 뒀고, 즉각적인 소프트웨어 변화로 이어지지는 않아요. 다만 AI 기업이 핵심 3D 개발 툴에 직접 투자한다는 사실 자체가 AI와 3D 창작 도구의 접점이 앞으로 더 깊어질 가능성을 시사하는 흥미로운 신호예요.</p><p>원문: <a href="https://80.lv/articles/claude-ai-creator-anthropic-joins-blender-development-fund-as-corporate-patron">80 Level</a></p>',
            source:      '80 Level',
            publishedAt: '2026.04.29',
            hue:         240,
            image:       'https://cdn.80.lv/api/upload/meta/48013/images/69f0f0a119d49/contain_1200x630.png',
            url:         'https://80.lv/articles/claude-ai-creator-anthropic-joins-blender-development-fund-as-corporate-patron',
            urls: [
                { label: '공식 발표', href: 'https://www.blender.org/press/anthropic-joins-the-blender-development-fund-as-corporate-patron/' },
            ],
        },
        {
            id:          'games-5dc1990d-2026-04',
            tab:         'games',
            headline:    'World Creator 2026.4 출시 — 게임·VFX용 GPU 지형 생성 툴에 무료 커뮤니티 에디션 등장',
            summary:     'BiteTheBytes가 World Creator 2026.4를 출시하고 내보내기만 제한된 무료 커뮤니티 에디션을 공개했어요.',
            body:        '<p>BiteTheBytes가 게임과 VFX 스튜디오에서 쓰이는 GPU 기반 지형 생성 소프트웨어 World Creator의 2026.4 버전을 출시했어요. 이번 업데이트에서는 수치 필드에서 수식 표현식을 직접 입력할 수 있게 돼 더 복잡한 지형 제어가 가능해졌고, 데칼 완전 지원과 지형 노멀 블렌딩 개선으로 히어로 오브젝트를 지형에 자연스럽게 통합할 수 있어요. VRAM 자동 조정 기능도 추가돼 씬 내 오브젝트 수가 GPU 메모리에 맞게 자동으로 최적화돼요. Blender, Unity, 언리얼 엔진, Godot, Houdini 등과 플러그인으로 연동됩니다.</p><p>이번 릴리즈에서 가장 눈에 띄는 변화는 새로 생긴 무료 커뮤니티 에디션이에요. 내보내기 기능만 비활성화된 완전한 기능의 체험판으로, 구매 전에 소프트웨어 전체를 자유롭게 테스트할 수 있어요. 인디 라이선스는 연 $49 임대 또는 $99 영구 구매로 이용할 수 있어요. Blizzard, Crytek, Blur Studio 같은 대형 스튜디오도 사용하는 툴인 만큼, 예산이 부족한 인디 개발자들도 이제 부담 없이 써볼 수 있게 됐어요.</p><p>원문: <a href="https://www.cgchannel.com/2026/04/world-creator-2026-4-is-out-with-a-new-free-community-edition/">CG Channel</a></p>',
            source:      'CG Channel',
            publishedAt: '2026.04.29',
            hue:         120,
            image:       'https://www.cgchannel.com/wp-content/uploads/2026/01/260127_WorldCreator20261_f.jpg',
            url:         'https://www.cgchannel.com/2026/04/world-creator-2026-4-is-out-with-a-new-free-community-edition/',
            urls: [
                { label: '변경사항 보기', href: 'https://docs.world-creator.com/release-notes/version-2026.x/world-creator-2026.4' },
            ],
        },
        {
            id:          'games-302650ff-2026-04',
            tab:         'games',
            headline:    'Adobe Photoshop 27.6, AI 오브젝트 회전과 반사 제거 기능 정식 출시',
            summary:     'Adobe Photoshop 27.6에 AI 오브젝트 회전과 반사 제거 등 인기 베타 기능들이 정식 출시됐어요.',
            body:        '<p>Adobe가 Photoshop 27.6을 출시하며 베타에서 인기를 끌었던 AI 기능들을 정식 버전으로 가져왔어요. \'오브젝트 회전(Rotate Object)\' 기능은 2D 컷아웃 이미지를 마치 3D 오브젝트처럼 원하는 각도로 돌려주는 생성형 AI 기능이에요. 배경 플레이트의 원근감에 맞춰 변환할 수 있어 컨셉 아트나 게임 텍스처 편집에 특히 유용해요. 다만 제너러티브 크레딧을 사용 당 20크레딧 소모하는 유료 기능이에요. \'반사 제거(Reflection Removal)\'는 유리창 뒤 피사체를 촬영한 사진의 반사 영상을 자동으로 제거하며, 별도 레이어에 비파괴적으로 처리돼요.</p><p>Generative Fill에는 Google Gemini 3.1과 Adobe Firefly Image 5 두 가지 신규 AI 모델이 추가됐어요. 레퍼런스 이미지를 여러 장 활용하는 기능도 생겨 Gemini에서는 최대 6장까지 참조할 수 있어요. 기존 Remove 툴도 업데이트돼 이제 일반 방해 요소 카테고리를 자동으로 감지하고 제거할 수 있어요. 게임 아트 제작에서 에셋을 다양한 각도로 빠르게 변형해야 할 때, 오브젝트 회전 기능은 상당한 시간 절약 효과를 기대할 수 있어요.</p><p>원문: <a href="https://www.cgchannel.com/2026/04/adobe-releases-photoshop-27-6/">CG Channel</a></p>',
            source:      'CG Channel',
            publishedAt: '2026.04.29',
            hue:         200,
            image:       'https://cdn.80.lv/api/upload/meta/48001/images/69f0bee4b3114/contain_1200x630.jpg',
            url:         'https://www.cgchannel.com/2026/04/adobe-releases-photoshop-27-6/',
            urls: [
                { label: '릴리즈 노트', href: 'https://helpx.adobe.com/photoshop/desktop/whats-new/photoshop-on-desktop-release-notes.html' },
            ],
        },
        {
            id:          'games-201001d2-2026-04',
            tab:         'games',
            headline:    'Adobe Firefly AI 어시스턴트 공개 베타 출시 — Photoshop·Premiere 등 60개 이상 툴 AI로 자동 연결',
            summary:     'Adobe가 Firefly AI 어시스턴트 공개 베타를 출시해 60개 이상의 크리에이티브 앱을 하나의 채팅 인터페이스에서 자동 연결해요.',
            body:        '<p>Adobe가 2026년 4월 27일부터 Firefly AI 어시스턴트를 전 세계 공개 베타로 출시했어요. Adobe의 창작 에이전트를 기반으로 한 이 도구는 사용자가 만들고 싶은 결과물을 자연어로 설명하면 포토샵, 프리미어, 일러스트레이터, 라이트룸 등 크리에이티브 앱 60개 이상에 걸쳐 다단계 워크플로를 자동으로 조율하고 실행해 줘요. 소셜 미디어 에셋 제작, 무드보드 생성, 인물 사진 리터칭, 제품 목업, 동영상 편집까지 복잡한 작업을 단 하나의 채팅 창에서 처리할 수 있어요. 어시스턴트가 진행 상황을 단계별로 보여 주며 중간에 방향을 바꾸거나 직접 개입할 수 있고, 완성된 결과물은 클라우드 스토리지에 바로 저장돼 어떤 Adobe 앱에서도 이어서 작업할 수 있어요.</p><p>게임 아트 파이프라인에서도 활용 가능성이 넓어졌어요. 텍스처 배치 보정, 컨셉 아트 리터칭, 예고편 영상 편집처럼 반복적이고 시간이 걸리는 작업을 AI가 자동으로 처리해 주면, 아티스트는 창의적 판단이 필요한 핵심 업무에 더 집중할 수 있어요. Adobe는 현재 외부 AI 모델과의 연동도 추진하고 있으며, Firefly 앱에는 이미 다양한 외부 생성 AI 모델이 통합되어 크리에이터의 선택 폭이 넓어지고 있어요.</p><p>이번 공개 베타는 Adobe가 내세우는 \'에이전틱 크리에이티비티\' 비전의 첫 번째 구체적인 결실이에요. 단순한 도구 모음을 넘어 창작 흐름 전체를 AI가 이해하고 지원하는 방식으로 전환되는 것을 보여 주며, 자동 색조 보정, 생성형 채우기, 배경 제거 등 전문가급 도구 60종 이상이 대화 맥락에 따라 자동 선택돼요. 앞으로 더 많은 기능이 순차적으로 추가될 예정이에요.</p><p>원문: <a href="https://blog.adobe.com/en/publish/2026/04/27/firefly-ai-assistant-public-beta">Adobe Blog</a></p>',
            source:      'Adobe Blog',
            publishedAt: '2026.04.28',
            hue:         210,
            image:       'https://blog.adobe.com/en/publish/2026/04/27/media_120f55e65ce82173a0e54777188bd1ce9cf51b27e.png?width=1200&format=pjpg&optimize=medium',
            url:         'https://blog.adobe.com/en/publish/2026/04/27/firefly-ai-assistant-public-beta',
            urls: [
                { label: '공식 사이트', href: 'https://www.adobe.com/products/firefly.html' },
            ],
        },
        {
            id: 'bytedance-seed3d-2-0427',
            tab: 'games',
            headline: "ByteDance, 게임 제작용 차세대 3D 생성 AI 'Seed3D 2.0' 공개",
            summary: 'ByteDance가 2단계 DiT 아키텍처로 기하학·PBR 텍스처를 대폭 강화한 Seed3D 2.0을 출시했어요.',
            body: '<p>ByteDance가 4월 23일 차세대 3D 생성 모델 Seed3D 2.0을 공식 출시했어요.<br/>2단계 DiT 아키텍처로 기하학적 정확도와 PBR 텍스처 품질을 대폭 높였고, 인간 선호도 평가에서 기하학 80%, 텍스처 69%로 기존 모델을 크게 앞질렀어요. API는 Volcano Engine에서 바로 사용할 수 있어요.<br/>게임·VR·물리 시뮬레이션 등 다양한 분야에서 \'생산 수준\' 3D 콘텐츠를 AI로 빠르게 만들 수 있게 되어, 아티스트와 개발자의 워크플로우가 크게 달라질 것 같아요!</p><p>원문: <a href="https://www.aibase.com/news/27393">AIbase</a></p>',
            source: 'AIbase',
            publishedAt: '2026.04.27',
            hue: 200,
            url: 'https://www.aibase.com/news/27393',
            urls: [
              { label: '프로젝트 보기', href: 'https://seed.bytedance.com/seed3d_2_0' },
            ],
        },
        {
            id: 'autodesk-wonder3d-0427',
            tab: 'games',
            headline: "Autodesk, 게임·영상 제작자를 위한 AI 3D 생성 도구 'Wonder 3D' 출시",
            summary: 'Autodesk Flow Studio에 텍스트·이미지를 USD·STL·OBJ 3D 에셋으로 변환하는 Wonder 3D 모델이 추가됐어요.',
            body: '<p>Autodesk가 자사 Flow Studio에 텍스트·이미지를 3D 에셋으로 변환하는 생성 AI 모델 Wonder 3D를 선보였어요.<br/>Text to 3D, Image to 3D, Text to Image 기능을 제공하며, 생성된 에셋은 USD·STL·OBJ 포맷으로 내보내 3D 프린팅이나 다른 DCC 툴에서 바로 활용할 수 있어요.<br/>전통적으로 많은 시간이 걸리던 3D 캐릭터·소품 제작 과정을 대폭 단축해 줘서, 인디 팀이나 소형 스튜디오에게도 AAA급 에셋 품질에 도전할 기회를 열어준다는 점이 포인트예요!</p><p>원문: <a href="https://adsknews.autodesk.com/en/news/autodesk-flow-studio-launches-wonder-3d-gen-ai-model-to-help-creators-make-3d-characters-and-objects-faster-and-easier/">Autodesk News</a></p>',
            source: 'Autodesk News',
            publishedAt: '2026.04.27',
            hue: 200,
            image: 'https://adsknews.autodesk.com/app/uploads/2026/04/AD_Wonder3D_boba-tea-wizard-1-1024x558.png',
            url: 'https://adsknews.autodesk.com/en/news/autodesk-flow-studio-launches-wonder-3d-gen-ai-model-to-help-creators-make-3d-characters-and-objects-faster-and-easier/',
        },
        {
            id: 'sparseal-wafer-pc-0426',
            tab: 'games',
            headline: "Sparseal, 3D 텍스처링 앱 'Wafer' PC 버전 출시",
            summary: 'NPR 에셋 제작에 특화된 3D 텍스처링 앱 Wafer가 iPad 전용에서 Windows PC로 확장됐어요.',
            body: '<p>Sparseal이 NPR(비사실적 렌더링) 에셋 제작에 특화된 3D 텍스처링 앱 Wafer의 Windows PC 버전을 출시했어요.<br/>기존 iPad 전용이었던 Wafer는 일러스트 소프트웨어의 친숙한 UI를 3D에 직접 적용한 방식으로, 스텐실·트리플래너 매핑·브러시 알파 등 다양한 에셋을 지원해요.<br/>저사양 기기에서도 원활하게 동작하는 최적화로 유명했던 Wafer가 PC로 확대되면서, 스타일라이즈드 게임 아트 작업자에게 더 넓은 선택지가 생겼어요.</p><p>원문: <a href="https://80.lv/articles/sparseal-launches-3d-texturing-app-wafer-for-pc/">80.lv</a></p>',
            source: '80.lv',
            publishedAt: '2026.04.26',
            hue: 200,
            image: 'https://cdn.80.lv/api/upload/meta/47948/images/69eb455fc466b/contain_1200x630.jpg',
            url: 'https://80.lv/articles/sparseal-launches-3d-texturing-app-wafer-for-pc/',
        },
        {
            id: 'roblox-agentic-ai-studio-0425',
            tab: 'games',
            headline: 'Roblox, AI 에이전트로 게임 제작 전 과정 자동화 시동',
            summary: 'Roblox Studio에 Planning Mode·Mesh Generation·자동 플레이테스트 등 에이전틱 AI 기능이 추가됐어요.',
            body: '<p>Roblox가 게임 개발 도구 \'Roblox Studio\'에 새로운 에이전틱 AI 기능을 추가했어요.<br/>\'Planning Mode\'로 복잡한 기획을 단계별 실행 계획서로 변환하고, Mesh Generation 기능으로 텍스처가 적용된 3D 메시를 텍스트 프롬프트만으로 바로 생성할 수 있게 됐어요. 자동 플레이테스트 에이전트도 새로 생겼고요.<br/>Roblox 상위 1,000명 크리에이터 중 이미 44%가 AI 도구를 쓰고 있다니, 앞으로 게임 제작 속도가 얼마나 빨라질지 기대되네요!</p><p>원문: <a href="https://techcrunch.com/2026/04/16/robloxs-ai-assistant-gets-new-agentic-tools-to-plan-build-and-test-games/">TechCrunch</a></p>',
            source: 'TechCrunch',
            publishedAt: '2026.04.25',
            hue: 200,
            image: 'https://techcrunch.com/wp-content/uploads/2026/02/roblox-header.jpg?resize=1200,800',
            url: 'https://techcrunch.com/2026/04/16/robloxs-ai-assistant-gets-new-agentic-tools-to-plan-build-and-test-games/',
            urls: [
              { label: 'Roblox 공식 발표', href: 'https://about.roblox.com/newsroom/2026/04/roblox-studio-going-agentic' },
            ],
        },
        {
            id: 'tripo-ai-h31-3d-generation-0425',
            tab: 'games',
            headline: 'Tripo AI, 고화질 AI 3D 생성 모델 H3.1 공개',
            summary: 'Tripo AI H3.1이 기하학 정확도와 텍스처 일관성을 강화해 수정 없이 프로덕션 투입이 가능한 3D 에셋을 제공해요.',
            body: '<p>Tripo AI가 새 이미지-to-3D 변환 모델 H3.1을 출시했어요.<br/>H3.1은 기존 모델 대비 지오메트리 정확도와 텍스처 일관성을 대폭 향상시켜서, 수작업 수정 없이 바로 프로덕션에 투입 가능한 에셋을 뽑아낼 수 있어요. 빠른 로우폴리 생성을 위한 Smart Mesh P1.0도 함께 공개됐어요.<br/>게임 개발·제품 시각화·인터랙티브 미디어 파이프라인에 AI 3D 에셋을 바로 넣을 수 있게 됐으니, 3D 아트 제작 시간이 확 줄어들 것 같아요!</p><p>원문: <a href="https://news.marketersmedia.com/tripo-ai-introduces-h31-to-advance-high-fidelity-ai-3d-generation-for-production/89189311">MarketersMEDIA</a></p>',
            source: 'MarketersMEDIA',
            publishedAt: '2026.04.25',
            hue: 200,
            url: 'https://news.marketersmedia.com/tripo-ai-introduces-h31-to-advance-high-fidelity-ai-3d-generation-for-production/89189311',
            urls: [
              { label: '바로가기', href: 'https://www.tripo3d.ai/features/image-to-3d-model/' },
            ],
        },
        {
            id: 'latitude-voyage-ai-rpg-0425',
            tab: 'games',
            headline: "Latitude, AI NPC와 대화하는 RPG 플랫폼 'Voyage' 공개",
            summary: 'AI Dungeon 개발사 Latitude가 텍스트만으로 AI 기반 RPG 세계를 설계하는 플랫폼 Voyage를 발표했어요.',
            body: '<p>AI Dungeon으로 유명한 Latitude가 플레이어가 직접 AI 기반 RPG 세계를 설계하는 플랫폼 \'Voyage\'를 발표했어요.<br/>지역·도시·랜드마크·퀘스트·빌런까지 텍스트로 설명하면 AI가 게임 코드와 세계관을 자동 생성해 주고, NPC 대화는 고정 스크립트 없이 AI가 실시간으로 반응해요.<br/>코딩이나 그래픽 작업 없이 누구나 RPG를 만들고 공유할 수 있다는 점에서, 게임 제작의 진입 장벽이 획기적으로 낮아질 것 같아요!</p><p>원문: <a href="https://techcrunch.com/2026/04/21/voyage-is-an-ai-rpg-platform-for-creating-custom-gaming-worlds-with-ai-generated-npc-interactions/">TechCrunch</a></p>',
            source: 'TechCrunch',
            publishedAt: '2026.04.25',
            hue: 200,
            image: 'https://techcrunch.com/wp-content/uploads/2026/04/Voyage-Promo-Art-3.jpg?w=1200',
            url: 'https://techcrunch.com/2026/04/21/voyage-is-an-ai-rpg-platform-for-creating-custom-gaming-worlds-with-ai-generated-npc-interactions/',
        },
        {
            id: 'autodesk-radical-mocap-0424',
            tab: 'games',
            headline: '오토데스크, AI 모션캡처 기술 기업 Radical 핵심 기술 전면 인수',
            summary: '단일 카메라 영상에서 배우 움직임을 추출하는 Radical의 AI 모캡 기술이 Maya 등 오토데스크 제품군에 통합될 예정이에요.',
            body: '<p>오토데스크가 단일 카메라 영상에서 배우의 움직임을 추출하는 AI 모션캡처 스타트업 Radical의 핵심 기술 및 IP를 완전 인수했어요.<br/>Radical Core는 FBX 포맷으로 애니메이션을 내보내고, Radical Live는 Maya·블렌더·유니티·언리얼 엔진 5에 실시간으로 스트리밍할 수 있었는데, 이 기술들이 오토데스크 제품군에 통합될 예정이에요.<br/>단일 카메라만으로도 전문 모캡 수준의 애니메이션이 가능해지는 이 기술이 Maya 등 게임 아트 파이프라인에 직접 녹아들 경우 제작 비용과 시간이 크게 줄어들 것으로 기대돼요!</p><p>원문: <a href="https://www.cgchannel.com/2026/04/autodesk-acquires-core-tech-of-ai-motion-capture-firm-radical/">CG Channel</a></p>',
            source: 'CG Channel',
            publishedAt: '2026.04.24',
            hue: 200,
            url: 'https://www.cgchannel.com/2026/04/autodesk-acquires-core-tech-of-ai-motion-capture-firm-radical/',
        },
        {
            id: 'blender-tire-rig-generator-0424',
            tab: 'games',
            headline: '블렌더용 타이어 자동 리깅 툴 무료 출시 — 복잡한 리깅 셋업을 한 번에',
            summary: '블렌더 플러그인 Tire Rig Generator가 압력·표면 변형까지 고려한 타이어 리깅 셋업을 메시 3개 입력만으로 자동 생성해줘요.',
            body: '<p>3D 아티스트 Raffael Kloten이 블렌더에서 타이어를 완전 자동으로 리깅해주는 무료 플러그인 \'Tire Rig Generator\'를 공개했어요.<br/>타이어 메쉬, 로우폴리 디포머 메쉬, 지면 메쉬만 입력하면 압력 변형과 표면 변형까지 고려한 복잡한 리깅 셋업을 자동으로 생성해준답니다.<br/>차량이 등장하는 게임이나 영상을 만드는 아티스트라면 타이어 리깅에 쏟던 시간을 확 줄일 수 있는 실용적인 도구라 주목받고 있어요!</p><p>원문: <a href="https://80.lv/articles/free-blender-tool-capable-of-auto-rigging-virtually-any-tire">80 Level</a></p>',
            source: '80 Level',
            publishedAt: '2026.04.24',
            hue: 200,
            image: 'https://cdn.80.lv/api/upload/meta/47932/images/69ea350bee72d/contain_1200x630.jpg',
            url: 'https://80.lv/articles/free-blender-tool-capable-of-auto-rigging-virtually-any-tire',
        },
        {
            id: 'capcom-gemini-playtesting-0423',
            tab: 'games',
            headline: '캡콤, 구글 클라우드 Gemini로 월 3만 시간 AI 플레이테스트 체제 구축',
            summary: '캡콤이 Gemini 에이전트 플랫폼으로 기존 5,280시간 작업을 72시간으로 단축하는 월 3만 시간 자율 플레이테스트 시스템을 구축했어요.',
            body: '<p>캡콤이 구글 클라우드의 Gemini 에이전트 플랫폼을 활용해 월 3만 시간 이상 자율 플레이테스트를 진행하는 AI 시스템을 구축했어요.<br/>기존에 사람이 5,280시간을 들여야 했던 시각 검사 작업을 AI 에이전트가 72시간 안에 처리하고 있고, BigQuery·Agent Development Kit도 함께 쓰이고 있대요.<br/>반복적인 QA를 AI에 맡기면서 개발자들이 진짜 창의적인 작업에 집중할 수 있게 됐다는 점에서, 대형 스튜디오 AI 도입의 실제 사례로 주목받고 있어요!</p><p>원문: <a href="https://www.googlecloudpresscorner.com/2026-04-22-How-Capcom-Is-Leading-the-Way-for-Enterprise-Agentic-AI">Google Cloud Press Corner</a></p>',
            source: 'Google Cloud Press Corner',
            publishedAt: '2026.04.23',
            hue: 200,
            url: 'https://www.googlecloudpresscorner.com/2026-04-22-How-Capcom-Is-Leading-the-Way-for-Enterprise-Agentic-AI',
        },
        {
            id: 'google-cloud-next-wand-0423',
            tab: 'games',
            headline: "구글 클라우드 Next 2026, 싱글플레이 PC게임용 AI 도우미 'Wand' 공개",
            summary: 'Google Cloud Next 2026에서 싱글플레이 PC게임 전용 AI 인게임 동반자 스타트업 Wand가 유망 게임 AI 스타트업으로 소개됐어요.',
            body: '<p>구글 클라우드 Next 2026 행사에서 싱글플레이 PC 게임 전용 AI 어시스턴트 스타트업 \'Wand\'가 주목받는 스타트업 중 하나로 소개됐어요.<br/>Wand는 게임 플레이 중 실시간으로 작동하는 인게임 AI 동반자로, 구글 클라우드의 인프라를 활용해 플레이어 경험을 개선하는 방향으로 개발 중이에요.<br/>Google Cloud Next 2026(4월 22~24일, 라스베이거스)에서 유망 게임 AI 스타트업으로 선정됐다는 건 게임 속 AI 동반자 기술이 빠르게 성숙하고 있다는 신호예요!</p><p>원문: <a href="https://techcrunch.com/2026/04/22/the-most-interesting-startups-showcased-at-google-cloud-next-2026/">TechCrunch</a></p>',
            source: 'TechCrunch',
            publishedAt: '2026.04.23',
            hue: 200,
            url: 'https://techcrunch.com/2026/04/22/the-most-interesting-startups-showcased-at-google-cloud-next-2026/',
        },
    
        
    /* ---- industry ---- */
        {
            id:          'industry-78c3e17b-2026-05',
            tab:         'industry',
            headline:    'GameMaker에 Claude Code 통합 — 자연어 명령으로 게임 제작 시대 열려',
            summary:     'GameMaker가 GM-CLI에 Claude Code를 내장해 자연어로 게임을 개발할 수 있는 환경을 열었어요.',
            body:        '<p>GameMaker가 새로운 런타임(GMRT)과 커맨드라인 툴체인 GM-CLI를 출시하면서 Anthropic의 Claude Code AI를 함께 내장했어요. 개발자가 터미널에서 자연어로 \'이걸 만들어줘\', \'버그 찾아줘\', \'이 빌드 설정 적용해줘\' 같은 명령을 치면 Claude Code가 알아서 처리해주는 방식으로, 전통적인 문법 기반 코딩 대신 대화형으로 게임을 개발하는 이른바 \'바이브 코딩\'이 2D 게임 엔진에서 본격적으로 가능해졌어요. GM-CLI는 기존 GameMaker 런타임과도 호환되며, GameMaker IDE를 실행하지 않고도 프로젝트 구조 조회, 버그 식별, 빌드 설정 관리 등의 작업을 AI와 함께 처리할 수 있어요.</p><p>AI 기능은 선택 사항으로 설계돼, 사용자가 원하는 수준에서만 활용할 수 있어요. GameMaker 총괄 러셀 케이는 "처음 게임을 만드는 초보자부터 프로 스튜디오까지 모두를 지원하고 싶었다"며, AI 통합이 특정 개발자층에 국한되지 않음을 강조했어요. 인디 개발자와 소규모 팀이 특히 많이 쓰는 GameMaker에 AI 코딩 보조가 탑재된 것은 의미가 커요. 대형 스튜디오에서나 가능했던 수준의 AI 지원을 1인 개발자도 터미널 한 줄로 누릴 수 있게 됐고, 이는 소규모 게임 개발의 속도와 접근성을 크게 바꿀 수 있는 전환점으로 평가돼요.</p><p>원문: <a href="https://www.gamedeveloper.com/production/gamemaker-incorporates-claude-code-to-enable-ai-assisted-workflows">Game Developer</a></p>',
            source:      'Game Developer',
            publishedAt: '2026.05.01',
            hue:         30,
            image:       'https://eu-images.contentstack.com/v3/assets/blt740a130ae3c5d529/blt6d7ae8c0053864b4/69f36810966e516c534470da/GameMaker_Header.png?disable=upscale&width=1200&height=630&fit=crop',
            url:         'https://www.gamedeveloper.com/production/gamemaker-incorporates-claude-code-to-enable-ai-assisted-workflows',
        },
        {
            id:          'industry-f2f68fe1-2026-04',
            tab:         'industry',
            headline:    '매직: 더 개더링 아레나 개발팀, AI 도입 보호 조항 요구하며 노조 결성',
            summary:     'MtG Arena 개발팀이 CWA와 연대해 노조를 결성하고 AI 도입 안전장치 마련을 요구했어요.',
            body:        '<p>Magic: The Gathering Arena 개발팀이 미국통신노조(CWA)와 연대하여 \'United Wizards of the Coast\'라는 노조를 결성했어요. 조합원 과반수 이상이 가입 카드에 서명했으며, 팀원들은 Wizards of the Coast와 모회사 Hasbro 경영진에게 노조의 자발적 승인을 공식 요청했어요. 노조는 해고 보호, 원격근무 보장, 생성형 AI 무분별한 도입에 대한 명확한 안전장치 마련을 핵심 요구사항으로 내걸었어요.</p><p>노조 측은 최근 경영진의 결정이 고용 안정에 대한 불확실성을 키웠으며, 명확한 안전장치 없이 AI 도입 압박이 커지고 있다고 주장했어요. 크런치와 인력 충원 없는 업무 가중도 문제로 제기됐어요. 자발적 승인이 이루어지지 않을 경우 전국노동관계위원회(NLRB)를 통한 공식 선거 절차를 진행할 계획이에요. AI 도구 채택 압박에 맞선 게임 개발자들의 집단 행동이 이어지면서, 스튜디오 내 AI 도입 방식과 노동자 보호에 대한 논의가 업계 전반으로 확산되고 있어요.</p><p>원문: <a href="https://www.pocketgamer.biz/magic-the-gathering-arena-team-unionises-under-cwa/">PocketGamer.biz</a></p>',
            source:      'PocketGamer.biz',
            publishedAt: '2026.04.30',
            hue:         10,
            image:       'https://media.pocketgamer.biz/images/139040/88850/magicthegatheringarenalogo-1_l1200.jpg',
            url:         'https://www.pocketgamer.biz/magic-the-gathering-arena-team-unionises-under-cwa/',
        },
        {
            id:          'industry-f27837d1-2026-04',
            tab:         'industry',
            headline:    '매직 더 개더링 아레나 개발자들, 생성형 AI 강요에 맞서 노조 결성 신청',
            summary:     'MTG Arena 개발팀 과반수가 생성형 AI 강요와 해고 위협에 맞서 CWA 산하 노조 결성을 신청했어요.',
            body:        '<p>Wizards of the Coast 산하 매직 더 개더링 아레나(MTG Arena) 개발팀의 과반수가 CWA(미국통신노조) 가입 의사를 밝히며 \'United Wizards of the Coast—CWA\'라는 이름으로 노조 결성을 공식 신청했어요. 이들은 NLRB(전국노동관계위원회)에 선거 청원서를 제출했고, Hasbro·WOTC 측에 2026년 5월 1일까지 자발적 인정을 요구했어요. 그러나 회사 측은 자발적 인정을 거부한 상태예요.</p><p>노조 추진의 주요 배경은 경영진이 LLM과 생성형 AI 도구 사용을 강요하면서도 직원들의 우려를 무시했다는 점이에요. 이 외에도 해고 보호, 원격 근무 보장, 지속 가능한 업무량, 명확한 커리어 경로, AI 가이드라인 수립 등이 핵심 요구 사항이에요. AI 도입에 대한 노동자 저항이 게임 업계에서 실제 단체 행동으로 이어진 사례라는 점에서, 이번 사건은 AI 도입 방식과 노동 권리를 둘러싼 업계 전반의 논쟁에 중요한 이정표가 될 것으로 보여요.</p><p>원문: <a href="https://www.gamedeveloper.com/business/magic-the-gathering-arena-devs-seek-to-unionise-to-deliver-genai-and-layoff-protections">Game Developer</a></p>',
            source:      'Game Developer',
            publishedAt: '2026.04.29',
            hue:         0,
            image:       'https://eu-images.contentstack.com/v3/assets/blt740a130ae3c5d529/blt2835fcf73fe16d06/69ef8a00b14e60ac0dfba60c/WOTC_Union.png?disable=upscale&width=1200&height=630&fit=crop',
            url:         'https://www.gamedeveloper.com/business/magic-the-gathering-arena-devs-seek-to-unionise-to-deliver-genai-and-layoff-protections',
            urls: [
                { label: 'CWA 성명', href: 'https://cwa-union.org/news/releases/wizards-coast-developers-form-union-cwa' },
            ],
        },
        {
            id:          'industry-45452650-2026-04',
            tab:         'industry',
            headline:    'GitHub Copilot, 구독제에서 사용량 기반 과금으로 전환 — AI 코딩 도구의 지속 불가능한 구조 드러나',
            summary:     'GitHub Copilot이 2026년 6월부터 월정액에서 토큰 사용량 기반 과금으로 전환해요.',
            body:        '<p>GitHub Copilot이 2026년 6월 1일부터 월정액 구독 방식을 버리고 토큰 사용량 기반 과금으로 전환한다고 밝혔어요. GitHub는 \'단순한 질문 하나와 몇 시간짜리 자율 코딩 세션이 같은 비용을 낸다\'는 구조적 문제를 지적하며, 현행 구독 모델이 \'지속 불가능\'하다고 인정했어요. 새 모델은 월별 AI 크레딧 한도를 제공하고, 초과분은 크레딧당 $0.01에 추가 구매하는 방식이에요. 연간 플랜은 폐지되며 월별 구독이나 무료 티어로 전환해야 해요.</p><p>에이전틱 AI 기능을 자주 쓰는 개발자라면 이전보다 비용이 크게 오를 수 있어요. 미사용 크레딧은 이월되지 않고 매월 초기화돼요. OpenAI Sora 서비스 종료에 이어, AI 도구들의 수익 모델이 한계에 부딪히면서 업계 전반에서 비용 구조가 재편되고 있다는 신호로 읽혀요. 게임 개발사들도 팀 내 Copilot 활용 방식과 예산 계획을 다시 점검해볼 필요가 있어요.</p><p>원문: <a href="https://www.gamedeveloper.com/production/github-copilot-is-pivoting-to-usage-based-billing-because-it-s-currently-unsustainable">Game Developer</a></p>',
            source:      'Game Developer',
            publishedAt: '2026.04.29',
            hue:         350,
            image:       'https://eu-images.contentstack.com/v3/assets/blt740a130ae3c5d529/blt177d8d26e29b2e79/69f09c5c6e88757c7ab0df0a/Github.png?disable=upscale&width=1200&height=630&fit=crop',
            url:         'https://www.gamedeveloper.com/production/github-copilot-is-pivoting-to-usage-based-billing-because-it-s-currently-unsustainable',
        },
        {
            id:          'industry-4daa63b1-2026-04',
            tab:         'industry',
            headline:    'Ubisoft Gen AI 리드, iicon 2026에서 \'AI가 크리에이티브 비전을 구현하는 방법\' 세션 발표',
            summary:     'Ubisoft Gen AI 총괄이 iicon 2026에서 AI가 게임 크리에이터의 창의적 비전을 어떻게 구현하는지 발표했어요.',
            body:        '<p>Ubisoft의 생성형 AI 총괄 Xavier Manzanares와 Google DeepMind의 프로덕트 리드 Alexandre Moufarek가 iicon 2026 게이밍 서밋(4월 27~29일, 라스베이거스)에서 함께 세션을 발표했어요. \'Building Worlds That Think: What Happens When AI Serves the Creative Vision\'이라는 제목의 이 브레이크아웃 세션은 4월 28일에 진행됐으며, 지능형 시스템이 어떻게 창작자에게 이전에는 존재하지 않던 경험을 만들어낼 힘을 부여하는지를 다뤘어요. iicon은 게임 업계 C레벨 임원들이 게임 전략의 최신 트렌드를 탐구하는 고위급 단독 서밋이에요.</p><p>이번 서밋에서 Ubisoft는 AI 세션 외에도 문화유산 보존과 인터랙티브 미디어 미래를 주제로 한 두 개의 추가 패널에 참여했어요. Ubisoft CEO Yves Guillemot도 Riot Games, Savvy Games Group CEO와 함께 인터랙티브 엔터테인먼트의 미래를 논의했어요. Ubisoft가 사내 AI 전문 조직을 공식 행사에 내세운 것은 생성형 AI를 게임 제작의 핵심 전략으로 공식화하고 있음을 명확히 보여주는 신호로 읽혀요.</p><p>원문: <a href="https://news.ubisoft.com/en-us/article/1Gg5iLsAiWHezEPiHAJDGu/ubisoft-at-iicon-2026">Ubisoft News</a></p>',
            source:      'Ubisoft News',
            publishedAt: '2026.04.29',
            hue:         30,
            image:       'https://staticctf.ubisoft.com/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/4Do368k4kpCQh9F6qYTEC7/54488062e4caf09f8f79568cf6fb4bf6/Ubisoft_Cloud_Logo.jpg',
            url:         'https://news.ubisoft.com/en-us/article/1Gg5iLsAiWHezEPiHAJDGu/ubisoft-at-iicon-2026',
        },
        {
            id:          'industry-db7e4ace-2026-04',
            tab:         'industry',
            headline:    '매직: 더 개더링 아레나 개발자 100여 명, AI 도입 압박 맞서 CWA 노조 결성',
            summary:     'WotC의 MTG: 아레나 개발팀이 해고·AI 강요·원격 근무 폐지에 맞서 CWA와 함께 공식 노조를 결성했어요.',
            body:        '<p>위저즈 오브 더 코스트(WotC)의 MTG: 아레나 개발팀 직원 100여 명이 2026년 4월 27일 미국 통신노동자연합(CWA)과 함께 공식 노조 결성을 선언했어요. 이미 과반수를 크게 넘는 직원들이 참여 의사를 밝혔으며, 5월 1일(국제 노동절) 이전에 모회사 해즈브로가 자발적으로 노조를 인정하지 않으면 전국노동관계위원회(NLRB)에 선거 청원을 제출할 예정이에요. 직원들은 소프트웨어 엔지니어, 아티스트, 디자이너 등 다양한 직군에 걸쳐 있어요.</p><p>노조 결성의 핵심 계기는 해즈브로가 단행한 두 차례의 대규모 해고였어요. 전체 직원의 약 3분의 1에 해당하는 2,000여 명이 영향을 받았고, 이후 원격 근무 폐지와 사무실 복귀 의무화 방침이 발표되면서 조직화가 가속화됐어요. 생성형 AI 관련 불만도 크게 작용했는데, 경영진이 LLM 등 AI 툴 사용을 강요하면서도 명확한 가이드라인이 없고, 개발자가 \'AI가 적합하지 않다\'고 판단해도 거부할 권리를 보장받지 못한다는 점이 핵심 쟁점으로 꼽혀요.</p><p>노조가 내세운 요구 사항은 해고 보호, 원격 근무 보장, 생성 AI 가이드라인 명확화, 과중 업무 방지, 경력 성장 체계, 개인 창작물 소유권, 지속 가능한 게임 개발 우선 등 7가지예요. MTG: 아레나는 수백만 명의 플레이어를 보유한 대형 온라인 카드 게임인 만큼, 이번 노조 결성이 게임 업계 전반의 AI 정책과 노동 관계에 미칠 파급력이 주목받고 있어요.</p><p>원문: <a href="https://kotaku.com/magic-the-gathering-arena-developers-unionize-layoff-remote-work-genai-protections-2000690932">Kotaku</a></p>',
            source:      'Kotaku',
            publishedAt: '2026.04.28',
            hue:         10,
            image:       'https://kotaku.com/app/uploads/2019/09/kgh5pkhlr9tlb6bhzmcd-1200x675.jpg',
            url:         'https://kotaku.com/magic-the-gathering-arena-developers-unionize-layoff-remote-work-genai-protections-2000690932',
            urls: [
                { label: '관련 보도', href: 'https://www.gamedeveloper.com/business/magic-the-gathering-arena-devs-seek-to-unionise-to-deliver-genai-and-layoff-protections' },
            ],
        },
        {
            id:          'industry-1d4d0b27-2026-04',
            tab:         'industry',
            headline:    '스퀘어 에닉스 현지화 담당, 팬 페스트서 AI 아트 써 뭇매',
            summary:     'FFXIV 팬 페스트 패널에서 코지 폭스가 AI 생성 이미지와 뮤직비디오를 사용하자 현장 관객과 온라인 팬들이 거세게 반발했다. 스퀘어 에닉스 CEO의 AI 도입 방침이 배경으로 지목됐다.',
            body:        '<p>파이널 판타지 XIV의 로컬라이제이션 담당자이자 작사가인 코지 폭스(Koji Fox)가 4월 25일 팬 페스트 패널 발표 중 AI 생성 이미지와 AI 제작 뮤직비디오를 활용해 팬 커뮤니티의 강한 반발을 불러일으켰다. 해당 기사는 4월 26일 보도됐다.</p><p>\'타코에서 텐더스까지: FFXIV의 가사 서빙\'이라는 제목의 패널에서 폭스는 마이크로소프트 <strong>코파일럿(Copilot)</strong>을 활용해 제작한 뮤직비디오를 공개했으며, 게임 사운드트랙에 참여한 뮤지션들의 AI 생성 초상 이미지도 사용했다. 폭스는 "시간 제약으로 공식 사진 사용 허가를 받지 못했다. CEO가 AI 도구 활용을 독려해왔기 때문에 AI로 이미지를 만들었는데, 결과적으로 성공이라고 하기 어렵다"고 자조적으로 해명했다.</p><p>현장 반응은 싸늘했다. 한 참석자는 소셜미디어에 "탄식 소리만 들릴 만큼 객석이 조용해졌다"고 전했으며, 온라인에서도 비판이 쏟아졌다. 일부 팬들은 이번 사태가 스퀘어 에닉스의 AI 우선 정책에 대한 폭스의 의도적인 항의일 수 있다고 해석했다. 스퀘어 에닉스 사장 키류 타카시는 2023년 "AI를 적극적으로 도입하겠다"는 입장을 공식적으로 밝힌 바 있다.</p>',
            source:      'Kotaku',
            publishedAt: '2026.04.27',
            hue:         345,
            url:         'https://kotaku.com/ff14-fanfest-panel-koji-fox-ai-art-square-enix-2000690711',
            urls: [
                { label: '관련 영상 (유튜브 라이브)', href: 'https://www.youtube.com/live/o9HMYdut2Ek' },
            ],
        },
        {
            id:          'industry-fb9b4156-2026-04',
            tab:         'industry',
            headline:    '구글 임원 "스튜디오 90%, AI 쓰면서도 공개 안 해"',
            summary:     '구글 클라우드 잭 뷰저 이사가 게임스컴 설문을 인용해 \'스튜디오 10곳 중 9곳이 AI 사용 중\'이라고 밝혔다. 대부분의 스튜디오는 여론 반발을 우려해 이 사실을 공개하지 않는다.',
            body:        '<p>구글 클라우드의 게임 부문 총괄 이사 잭 뷰저(Jack Buser)가 "지금 플레이어들이 즐기는 게임 대부분은 이미 AI로 만들어진 것"이라고 밝혀 업계의 이목을 집중시켰다.</p><p>뷰저는 게임스컴(Gamescom) 현장에서 진행된 설문 결과를 인용, "게임 개발자 10명 중 9명이 \'AI 도구를 사용 중\'이라고 답했다"고 밝혔다. 그러나 GDC의 공식 개발자 조사에선 AI 사용률이 약 36%로 집계되는 등 공개 수치와 실제 현황 사이에 큰 괴리가 있다는 게 그의 주장이다.</p><p>왜 스튜디오들은 침묵할까. 뷰저에 따르면 많은 기업들이 여론 반발과 브랜드 이미지 훼손을 우려해 AI 도입 사실을 대외적으로 밝히지 않는다. \'AI가 인간의 창의성을 대체한다\'는 인식이 게이머 사이에 확산되면서, 스튜디오들은 조용히, 그러나 적극적으로 AI를 도입하는 이중적 행보를 보이고 있다.</p><p>실제 사례로 뷰저는 캡콤을 언급했다. 캡콤은 구글의 AI 도구(Gemini, Nano Banana Pro 등)를 활용해 오픈 월드를 채우는 배경 아트와 소품 등 보조 에셋을 AI로 제작하고 있다. 핵심 캐릭터와 스토리 관련 자산은 여전히 인간 아티스트가 담당하지만, 반복적이고 대량으로 필요한 배경 요소에는 AI가 빠르게 투입되고 있다.</p><p>뷰저는 AI의 핵심 가치로 개발 속도 혁신을 꼽았다. "과거엔 게임 1개 제작에 7년이 걸렸지만, 이제 같은 시간에 5개를 만들 수 있다"는 것이다. 한편 모건 스탠리는 AI 기반 비용 절감이 게임 산업에 연간 최대 220억 달러(약 30조 원)의 추가 수익을 창출할 수 있다고 전망한 바 있다.</p><p>원문: <a href="https://futurism.com/artificial-intelligence/google-exec-video-games-secretly-ai">Futurism</a></p>',
            source:      'Futurism',
            publishedAt: '2026.04.26',
            hue:         20,
            url:         'https://futurism.com/artificial-intelligence/google-exec-video-games-secretly-ai',
        },
        {
            id: 'playdate-catalog-no-genai-0427',
            tab: 'industry',
            headline: '플레이데이트 콘솔, 생성 AI 아트·음악·텍스트 사용 게임 등록 금지 선언',
            summary: 'Panic이 플레이데이트 카탈로그에서 이미지·오디오·텍스트에 생성 AI를 사용한 게임을 받지 않기로 공식 선언했어요.',
            body: '<p>소형 게임기 플레이데이트 제조사 Panic이 이달부터 자사 카탈로그에서 이미지·오디오·음악·텍스트 등에 생성 AI를 사용한 게임을 받지 않기로 했어요.<br/>ChatGPT, Stable Diffusion, Suno 등 주요 AI 생성 도구가 모두 금지 대상이며, AI 코딩 보조(Lua 디버깅 등)는 허용하되 사용 여부를 사용자에게 공개해야 해요.<br/>플랫폼이 AI 생성 콘텐츠에 명확한 기준을 세운 드문 사례로, 인디 게임 커뮤니티에서 AI 사용 정책 논쟁에 불을 지필 것 같아요!</p><p>원문: <a href="https://www.engadget.com/gaming/panic-says-the-playdate-catalog-wont-accept-games-made-with-generative-ai-160615022.html">Engadget</a></p>',
            source: 'Engadget',
            publishedAt: '2026.04.27',
            hue: 30,
            image: 'https://s.yimg.com/ny/api/res/1.2/caORjw3ZYOGvOMNf5rHlQg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/img_1771_7378.jpg',
            url: 'https://www.engadget.com/gaming/panic-says-the-playdate-catalog-wont-accept-games-made-with-generative-ai-160615022.html',
            urls: [
              { label: '정책 보기', href: 'https://help.play.date/catalog-developer/ai-disclosure/' },
            ],
        },
        {
            id: 'xbox-ai-strategy-review-0426',
            tab: 'industry',
            headline: "Xbox, AI 전략 재검토 선언 — '데일리 액티브 플레이어'를 새 핵심 지표로",
            summary: '마이크로소프트가 Xbox 브랜드로 복귀하면서 새 CEO Asha Sharma가 AI 접근 방식과 독점 전략 전면 재검토를 공식 발표했어요.',
            body: '<p>마이크로소프트가 \'Microsoft Gaming\' 브랜드를 버리고 Xbox 이름으로 복귀하면서, AI 접근 방식과 독점 전략을 재검토하겠다고 공식 발표했어요.<br/>새 CEO Asha Sharma는 구성원에게 보낸 메모에서 Xbox의 새 핵심 목표로 \'일간 활성 플레이어(DAP) 성장\'을 내세우고, 콘솔·모바일·신흥시장 확대 방향을 함께 제시했어요.<br/>Xbox가 AI 전략을 공개적으로 재고한다고 밝힌 만큼, 앞으로 게임 개발 및 서비스 운영에서 AI 활용 방향이 어떻게 바뀔지 주목돼요.</p><p>원문: <a href="https://www.gamesindustry.biz/microsoft-gaming-reverts-to-xbox-branding">GamesIndustry.biz</a></p>',
            source: 'GamesIndustry.biz',
            publishedAt: '2026.04.26',
            hue: 30,
            image: 'https://assetsio.gnwcdn.com/xbox-series-x_lxcHHt4.png?width=1200&height=630&fit=crop&enable=upscale&auto=webp',
            url: 'https://www.gamesindustry.biz/microsoft-gaming-reverts-to-xbox-branding',
        },
        {
            id: 'identity-v-netease-ai-boycott-0425',
            tab: 'industry',
            headline: 'Identity V 팬들, NetEase의 AI 아트 무단 사용에 불매 운동 선언',
            summary: 'Identity V 커뮤니티가 NetEase의 AI 생성 이미지 무단 사용과 아티스트 해고 의혹에 집단 불매 운동을 벌였어요.',
            body: '<p>모바일 게임 Identity V의 팬 커뮤니티가 개발사 NetEase의 AI 생성 이미지 무단 사용에 반발해 4월 23일 집단 불매 운동을 벌였어요.<br/>커뮤니티 조사에 따르면 COA IV 트레일러, 홍보 영상, 소셜 미디어 아트 등에서 AI 생성 흔적이 발견됐고, NetEase가 산하 스튜디오 Joker Studios 아티스트를 해고하면서 AI로 대체했다는 의혹도 나왔어요.<br/>아직 NetEase의 공식 입장이 없다는 게 더 화제인데, 게임 업계에서 AI 도입 방식이 얼마나 민감한 사안인지 다시 한번 보여주는 사례예요.</p><p>원문: <a href="https://news.bittopup.com/news/identity-v-ai-backlash-2026-is-the-april-23-boycott-worth-it">BitTopup News</a></p>',
            source: 'BitTopup News',
            publishedAt: '2026.04.25',
            hue: 30,
            url: 'https://news.bittopup.com/news/identity-v-ai-backlash-2026-is-the-april-23-boycott-worth-it',
            urls: [
              { label: '청원 보기', href: 'https://www.change.org/p/stop-ai-in-idv' },
            ],
        },
        {
            id: 'makko-ai-2d-game-studio-0425',
            tab: 'industry',
            headline: 'Makko AI, 누구나 쓸 수 있는 AI 2D 게임 스튜디오 정식 출시',
            summary: '드로잉·코딩 없이 대화만으로 2D 게임 에셋을 만드는 Makko AI가 베타에서 4만 개 이상 에셋을 생성하고 정식 출시됐어요.',
            body: '<p>Makko AI가 드로잉·애니메이션·코딩 지식 없이도 2D 게임 에셋을 만들 수 있는 AI 게임 스튜디오를 4월 20일 정식 공개했어요.<br/>베타 기간 동안 수천 명의 유저가 3,000개 이상의 게임·프로토타입을 만들었고, 40,000개 이상의 에셋이 생성됐어요. \'Collections\' 기능으로 캐릭터·환경·소품·UI 에셋의 스타일 일관성을 유지하면서 대화형으로 제작할 수 있어요.<br/>프로그래밍이나 아트 스킬이 없는 1인 개발자도 코히런트한 2D 게임 에셋을 뽑을 수 있다는 게 진짜 게임 체인저네요!</p><p>원문: <a href="https://itbusinessnet.com/2026/04/makko-launches-ai-powered-2d-game-studio-with-over-40000-game-assets-created-in-beta/">IT Business Net</a></p>',
            source: 'IT Business Net',
            publishedAt: '2026.04.25',
            hue: 30,
            url: 'https://itbusinessnet.com/2026/04/makko-launches-ai-powered-2d-game-studio-with-over-40000-game-assets-created-in-beta/',
            urls: [
              { label: 'makko.ai 바로가기', href: 'https://makko.ai' },
            ],
        },
        {
            id: 'gdc-2026-layer-ai-recap-0425',
            tab: 'industry',
            headline: "GDC 2026: 게임 스튜디오의 AI 도입, 이제는 '어떻게 운영하나'가 핵심",
            summary: 'Layer AI의 GDC 2026 리캡 — AI 도입 찬반은 끝났고, 대형 스튜디오는 UA·라이브옵스 파이프라인 자동화 체계 구축에 집중 중이에요.',
            body: '<p>Layer AI가 GDC 2026 현장 리캡을 통해 대형 게임 스튜디오들의 AI 크리에이티브 생산 도입 현황을 공유했어요.<br/>UA·라이브옵스 팀이 숏폼 영상 광고, 앱스토어 프리뷰, 소셜 트레일러 등을 훨씬 빠른 속도로 만들기 위해 AI를 전면 도입하고 있고, Layer처럼 IP 안전성·데이터 프라이버시를 보장하는 엔터프라이즈 솔루션 수요가 급증하고 있다고 해요.<br/>1~2년 전만 해도 \'AI를 써도 되나?\'를 논쟁했다면, GDC 2026에서는 \'AI 파이프라인을 어떻게 확장할까?\'가 주제였다는 점이 인상적이에요.</p><p>원문: <a href="https://www.layer.ai/blog/gdc-2026-recap-how-ai-workflows-are-transforming-ua-creative-production-for-game-studios">Layer AI Blog</a></p>',
            source: 'Layer AI Blog',
            publishedAt: '2026.04.25',
            hue: 30,
            image: 'https://www.layer.ai/_astro/coverImage.BqZiG5rZ.png',
          url: 'https://www.layer.ai/blog/gdc-2026-recap-how-ai-workflows-are-transforming-ua-creative-production-for-game-studios',
        },
        {
            id: 'jason-schreier-studios-ai-claude-0424',
            tab: 'industry',
            headline: "제이슨 슈라이어 '거의 모든 대형 스튜디오가 Claude 등 생성 AI 도구 활용 중'",
            summary: '저명한 게임 저널리스트 제이슨 슈라이어가 거의 모든 대형 게임 스튜디오가 생성형 AI 도구를 개발에 적극 사용 중이라고 확인했어요.',
            body: '<p>저명한 게임 저널리스트 제이슨 슈라이어가 거의 모든 대형 게임 스튜디오가 Claude를 비롯한 생성형 AI 도구를 개발에 적극 사용하고 있다고 확인했어요.<br/>구글 임원의 발언에 이어 나온 이 증언으로, 업계 내부에서는 AI 사용이 이미 일반화됐지만 공개적 반응이 두려워 외부에는 알리지 않는 관행이 드러났죠.<br/>Embark Studios의 Arc Raiders AI 보이스 라인 사례처럼 일부 스튜디오가 먼저 공개했다 역풍을 맞은 경험이 있어, 업계의 투명성 딜레마가 점점 커지고 있어요!</p><p>원문: <a href="https://www.thegamer.com/game-studios-using-generative-ai-claude-in-development/">TheGamer</a></p>',
            source: 'TheGamer',
            publishedAt: '2026.04.24',
            hue: 30,
            image: 'https://static0.thegamerimages.com/wordpress/wp-content/uploads/wm/2026/04/2026040812180100_c-1.jpg?w=1600&h=900&fit=crop',
            url: 'https://www.thegamer.com/game-studios-using-generative-ai-claude-in-development/',
        },
        {
            id: 'morgan-stanley-game-ai-savings-0423',
            tab: 'industry',
            headline: '모건스탠리: AI로 게임 개발비 절반 줄이면 업계 연간 220억 달러 추가 수익 가능',
            summary: '모건스탠리가 AI 도입으로 게임 개발 비용을 절반 줄일 수 있고 업계 연간 약 220억 달러 추가 이익이 가능하다고 분석했어요.',
            body: '<p>모건스탠리가 AI 도구 도입으로 게임 개발 비용을 최대 절반가량 줄일 수 있고, 전 세계 게임사가 연간 약 220억 달러의 이익을 추가 창출할 수 있다는 분석을 내놨어요.<br/>게임 환경 생성, 대화 생성, 소프트웨어 테스트 자동화 등에 AI를 쓰면 개발 일정이 단축되고 소규모 팀 운영도 가능해진대요. 텐센트·소니·로블록스·EA·유비소프트 등이 주요 수혜 기업으로 꼽혔어요.<br/>GTA VI 같은 초대형 프로젝트가 수년씩 걸리는 현실을 생각하면, AI가 개발 주기를 단축시켜 준다는 분석은 게임사 입장에서 정말 주목할 만한 얘기예요!</p><p>원문: <a href="https://www.freemalaysiatoday.com/category/business/2026/04/22/gaming-industry-could-unlock-us22bil-from-ai-cost-cuts-says-morgan-stanley">Free Malaysia Today</a></p>',
            source: 'Free Malaysia Today',
            publishedAt: '2026.04.23',
            hue: 30,
            image: 'https://www.freemalaysiatoday.com/cdn-cgi/image/quality=75,format=auto,fit=cover,dpr=1,width=1200,height=630,gravity=center/https://media.freemalaysiatoday.com/wp-content/uploads/2026/04/edc895d3-afp__20231205__34728p6__v1__highres__rockstargamesreleasesfirsttrailerforgrandthefta_cropped_1.webp',
            url: 'https://www.freemalaysiatoday.com/category/business/2026/04/22/gaming-industry-could-unlock-us22bil-from-ai-cost-cuts-says-morgan-stanley',
        },
        
    /* ---- art ---- */
        {
            id:          'art-b15b362a-2026-05',
            tab:         'art',
            headline:    'Spotify, 인간 아티스트 인증 배지 출시 — AI 음악과 구별한다',
            summary:     '스포티파이가 실제 인간 아티스트를 증명하는 \'Verified by Spotify\' 배지를 출시했어요.',
            body:        '<p>스포티파이가 실제 사람이 만든 음악임을 증명하는 \'Verified by Spotify\' 초록색 배지 시스템을 출시했어요. 배지를 받으려면 공연 일정, 굿즈 판매, 연결된 소셜 계정 등 플랫폼 밖에서의 활동 흔적이 있어야 하고, 일시적인 인기가 아닌 꾸준한 청취자 참여도 증명해야 해요. AI 음악이나 AI 페르소나를 주로 사용하는 아티스트 프로필은 인증 자격이 아예 없으며, 배지는 아티스트 프로필과 검색 결과에 표시돼요. 출시 시점에 이미 검색 활동이 있는 아티스트의 99% 이상이 인증을 받게 될 예정으로, 그 대부분은 다양한 장르와 지역의 인디 아티스트들이에요.</p><p>이번 조치는 스트리밍 플랫폼을 가득 채우고 있는 저품질 AI 생성 음악 문제에 대응하기 위한 것이에요. Deezer에 따르면 현재 매일 업로드되는 트랙의 44%가 AI 생성 음악이며, Sony Music도 이전에 AI가 아티스트를 흉내 낸 트랙 135,000개 이상의 삭제를 요청한 바 있어요. 스포티파이는 배지와 함께 아티스트 프로필에 경력 이정표, 발매 이력, 투어 정보를 강조하는 새 섹션도 추가해, 청취자가 진짜 아티스트를 더 쉽게 찾고 연결할 수 있도록 지원해요. AI 생성 콘텐츠가 넘쳐나는 시대에 \'진짜 인간 창작자\'를 구별해 주는 이 시도는 음악 업계 전반에 새로운 기준을 제시할 것으로 보여요.</p><p>원문: <a href="https://techcrunch.com/2026/04/30/spotify-introduces-verified-artist-badges-to-help-distinguish-humans-from-ai/">TechCrunch</a></p>',
            source:      'TechCrunch',
            publishedAt: '2026.05.01',
            hue:         130,
            image:       'https://techcrunch.com/wp-content/uploads/2026/04/S4A_Verified_Header_Ravyn.jpg?resize=1200,683',
            url:         'https://techcrunch.com/2026/04/30/spotify-introduces-verified-artist-badges-to-help-distinguish-humans-from-ai/',
            urls: [
                { label: '공식 발표', href: 'https://newsroom.spotify.com/2026-04-30/verified-by-spotify-badge-artist-details/' },
            ],
        },
        {
            id:          'art-598ee92f-2026-05',
            tab:         'art',
            headline:    'COMFYUI-PBRFusion4',
            summary:     'ComfyUI에서 PBR 텍스처용 깊이 맵·노멀 맵을 생성하는 노드의 의존성 목록이 명확하게 정리됐어요.',
            body:        '<p>COMFYUI-PBRFusion4는 입력 이미지로부터 깊이 맵(depth map)과 노멀 맵(normal map)을 자동으로 생성해주는 ComfyUI 커스텀 노드예요. PBR(물리 기반 렌더링) 텍스처 제작 워크플로에 바로 연결할 수 있어, 텍스처 아티스트가 재질 표면의 입체감과 반사 특성을 훨씬 빠르게 구현하는 데 유용해요. 이번 버전 1.0.3 업데이트에서는 README에 의존성 패키지 목록이 명확하게 추가돼, 새로 설치하는 사용자의 진입 장벽이 한결 낮아졌어요.</p><p>이번 커밋에서는 README의 Requirements 섹션에 huggingface-hub, numpy, opencv-python-headless, safetensors, torch, transformers 등 여섯 가지 핵심 의존성이 명시적으로 정리됐어요. 특히 ComfyUI처럼 GUI 없이 동작하는 서버 환경에서는 opencv-python 대신 opencv-python-headless로 충분하다는 안내도 함께 달렸어요. pyproject.toml과 requirements.txt도 함께 업데이트되며 패키지 구성이 전체적으로 일관되게 정돈됐어요. 의존성 정보가 명확해지면 처음 설치하는 사용자의 오류가 줄어들고, 헤드리스 ComfyUI 환경에서도 노드를 안정적으로 활용할 수 있게 돼 실무에서의 활용도가 높아질 거예요.</p><p>원문: <a href="https://github.com/Night1099/COMFYUI-PBRFusion4/commit/17687f480f9412e2e302290cb80eb7951cce1485">Night1099/COMFYUI-PBRFusion4</a></p>',
            source:      'Night1099/COMFYUI-PBRFusion4',
            publishedAt: '2026.05.01',
            hue:         60,
            image:       'https://opengraph.githubusercontent.com/1/Night1099/COMFYUI-PBRFusion4',
            url:         'https://github.com/Night1099/COMFYUI-PBRFusion4/commit/17687f480f9412e2e302290cb80eb7951cce1485',
        },
        {
            id:          'art-6fc6e2a6-2026-04',
            tab:         'art',
            headline:    'Runway CEO "AI 영상 생성은 서막일 뿐 — 월드 모델이 다음 목적지"',
            summary:     'Runway CEO가 AI 영상 생성은 게임·로보틱스까지 아우르는 월드 모델 개발의 출발점일 뿐이라고 밝혔어요.',
            body:        '<p>Runway의 공동창업자이자 CEO인 크리스토발 발렌수엘라가 TechCrunch Equity 팟캐스트에 출연해 AI 영상 생성의 미래와 회사의 비전을 밝혔어요. 그는 AI 영상 생성이 단순한 콘텐츠 제작 도구를 넘어, 게임·로보틱스·AGI까지 아우르는 \'월드 모델\' 개발의 출발점에 불과하다고 말했어요. Runway는 약 8억 6천만 달러의 투자를 유치해 53억 달러 밸류에이션을 기록 중이며, 구글·오픈AI와 직접 경쟁하고 있어요.</p><p>발렌수엘라가 추구하는 월드 모델은 물리 법칙을 이해하는 범용 세계 시뮬레이터로, 경쟁사들과는 차별화된 방향성이에요. 실시간 영상 생성 기술이 현실화되면 콘텐츠 제작을 훨씬 넘어서는 \'비선형 미디어\'와 인터랙티브 엔터테인먼트가 가능해져, 창작물 제작의 패러다임 자체가 근본적으로 바뀔 것으로 전망했어요. 기술이 영화 제작에서 실제 제약 요소라는 관점에서, 그 제약이 사라질 때 어떤 변화가 생길지를 탐구하는 것이 Runway의 핵심 과제라고 강조했어요.</p><p>원문: <a href="https://techcrunch.com/podcast/equity-podcast-runway-ceo-cristobal-valenzuela-ai-video-world-models/">TechCrunch</a></p>',
            source:      'TechCrunch',
            publishedAt: '2026.04.30',
            hue:         290,
            image:       'https://techcrunch.com/wp-content/uploads/2026/04/GettyImages-2250760741.jpg',
            url:         'https://techcrunch.com/podcast/equity-podcast-runway-ceo-cristobal-valenzuela-ai-video-world-models/',
        },
        {
            id:          'art-ffacf63e-2026-04',
            tab:         'art',
            headline:    'Midjourney V8 알파: 더 빠르고 정밀해진 AI 이미지 생성, 7가지 실전 교훈',
            summary:     'Midjourney V8 알파가 V7 대비 4~5배 빠른 속도와 향상된 프롬프트 추종력으로 주목받고 있어요.',
            body:        '<p>Midjourney가 2026년 3월 17일 알파 출시한 V8 모델이 점점 더 많은 주목을 받고 있어요. 실사용 리뷰에 따르면 표준 해상도 기준으로 V7보다 4~5배 빠르게 이미지를 생성해요. 4월 14일 출시된 V8.1 알파에서는 HD 모드도 훨씬 빠르고 저렴해졌어요. 프롬프트 추종력·이미지 일관성·복잡한 장면의 세부 표현도 개선됐으며, 인용부호 안의 텍스트 렌더링 정확도도 높아졌어요. 개인화, 무드보드, 스타일 레퍼런스를 통한 스타일 제어도 강화됐어요.</p><p>아직 알파 단계라 V7이 기본 모델로 유지되고 있으며, V8 생성물은 메인 사이트가 아닌 별도의 알파 사이트에서만 이용할 수 있어요. Relax 모드는 이후 Standard, Pro, Mega 구독자에게 추가됐고, V7 프로필과의 하위 호환성도 지원돼요. 일부 고가 옵션 조합은 아직 지원되지 않는 제한도 있어요. 아직 정식 출시가 아니지만 아티스트·디자이너·컨셉 아트팀이라면 지금부터 V8의 특성을 익혀두는 것이 나중에 유리할 수 있어요.</p><p>원문: <a href="https://www.progressiverobot.com/2026/04/28/midjourney-v8/">Progressive Robot</a></p>',
            source:      'Progressive Robot',
            publishedAt: '2026.04.29',
            hue:         290,
            image:       'https://www.progressiverobot.com/wp-content/uploads/2026/04/midjourney-v8-featured-16x9-v1.jpg',
            url:         'https://www.progressiverobot.com/2026/04/28/midjourney-v8/',
            urls: [
                { label: '업데이트 보기', href: 'https://www.midjourney.com/updates' },
            ],
        },
        {
            id:          'art-7155cf87-2026-04',
            tab:         'art',
            headline:    'OpenAI Sora 서비스 종료가 드러낸 AI 영상 생성의 한계 — 창의 분야 AI의 지속 가능성 의문',
            summary:     'OpenAI가 일 $100만 적자를 낸 Sora를 종료하면서 AI 창의 도구의 수익성 한계가 드러났어요.',
            body:        '<p>OpenAI가 2026년 4월 26일 AI 영상 생성 서비스 Sora를 공식 종료했어요. 연구자의 분석에 따르면 Sora는 운영 중 하루 $100만의 손실을 기록했어요. 영상 생성은 텍스트나 이미지 생성보다 훨씬 많은 컴퓨팅 자원을 필요로 해 비용 통제가 어렵고, 초기 열기가 식은 뒤 크리에이티브 전문가들이 실제 워크플로에 통합하지 않으면서 사용자 이탈이 빨랐어요. 저작권·지적재산 문제로 인한 표현 제한도 활용 범위를 좁혔어요. 경쟁은 Runway, Kling, Google Veo 위주로 재편됐어요.</p><p>분석가는 AI 창의 도구가 \'익숙한 패턴을 복제\'하도록 학습되어 진정한 독창성을 억제하는 \'창의 역편향\' 문제를 지적해요. 또한 텍스트 프롬프트 중심 창작이 예술적 능력보다 프롬프트 작성 능력을 요구한다는 점도 한계로 꼽혀요. GitHub Copilot의 과금 전환에 이어, \'화려한 시연 → 실제 사용자 이탈\' 패턴이 반복된다면 어떤 AI 창의 도구가 장기적으로 살아남을지 업계 전체가 다시 고민해야 할 시점이에요.</p><p>원문: <a href="https://techxplore.com/news/2026-04-sora-shutdown-reveals-limits-ai.html">TechXplore / The Conversation</a></p>',
            source:      'TechXplore / The Conversation',
            publishedAt: '2026.04.29',
            hue:         10,
            image:       'https://scx2.b-cdn.net/gfx/news/hires/2023/openai-1.jpg',
            url:         'https://techxplore.com/news/2026-04-sora-shutdown-reveals-limits-ai.html',
        },
        {
            id:          'art-1cf236bd-2026-04',
            tab:         'art',
            headline:    '테일러 스위프트, AI 딥페이크 막으려 목소리·이미지 상표 출원',
            summary:     '테일러 스위프트가 USPTO에 목소리 및 이미지 상표 3건을 출원해 AI 딥페이크 대응의 새로운 법적 전략을 제시했어요.',
            body:        '<p>테일러 스위프트의 권리 관리 회사 TAS Rights Management가 2026년 4월 24일부터 27일 사이에 미국 특허상표청(USPTO)에 상표 3건을 출원했어요. 음성 상표 2건은 각각 \'"Hey, it\'s Taylor Swift"\'와 \'"Hey, it\'s Taylor"\'라는 음성 문구이며, 시각 상표 1건은 핑크 기타를 들고 무지갯빛 바디수트를 입은 공연 중 사진이에요. 이번 출원은 배우 매튜 매코너헤이가 2025년 자신의 유명 대사 음성 상표 8건을 확보한 법적 전략을 따른 것으로, 지식재산권 전문 변호사 조시 거벤이 공개해 주목받았어요.</p><p>상표권이 AI 딥페이크 대응 수단으로 주목받는 이유는 기존 퍼블리시티권을 보완하는 추가적인 법적 구제 수단이 될 수 있기 때문이에요. 저작권처럼 AI 플랫폼에 테이크다운 요청이 가능해지며, 2025년 12월 디즈니가 자사 캐릭터 무단 생성과 관련해 구글에 상표권 근거 경고장을 보낸 것이 가장 최근의 선례로 꼽혀요. 스위프트는 딥페이크 포르노그래피, AI 챗봇 무단 사용, 2024년 트럼프 지지 이미지 유포 등 다양한 AI 악용 피해를 직접 겪어 왔어요.</p><p>상표권의 AI 딥페이크 대응 효력은 아직 법원에서 검증되지 않았지만, 유명인 목소리와 이미지를 AI가 무단 복제하는 사례가 급증하는 상황에서 상표권이 퍼블리시티권을 보완하는 새로운 법적 방패로 떠오르고 있어요. 법조계는 이 전략이 엔터테인먼트 업계 전반으로 확산될지 주목하고 있어요.</p><p>원문: <a href="https://variety.com/2026/music/news/taylor-swift-trademark-voice-likeness-ai-misuse-1236731401/">Variety</a></p>',
            source:      'Variety',
            publishedAt: '2026.04.28',
            hue:         320,
            image:       'https://variety.com/wp-content/uploads/2025/09/GettyImages-2166934862.jpg?crop=0px%2C103px%2C5000px%2C2812px&resize=1000%2C563',
            url:         'https://variety.com/2026/music/news/taylor-swift-trademark-voice-likeness-ai-misuse-1236731401/',
        },
        {
            id:          'art-91b9db7b-2026-04',
            tab:         'art',
            headline:    'DNE·Gracia, AI 기반 4D 가우시안 스플래팅으로 4분짜리 음악 공연 실시간 스트리밍 성공',
            summary:     'LA의 DNE와 Gracia가 4DGS 기술로 4분짜리 음악 공연을 앱 없이 웹 브라우저에서 실시간 재생하는 데 성공했어요.',
            body:        '<p>LA 기반의 볼류메트릭 캡처 스튜디오 DNE(Digital Nation Entertainment)와 인프라 기업 Gracia가 4D 가우시안 스플래팅(4DGS) 기술로 촬영한 4분짜리 음악 공연을 앱 다운로드 없이 웹 브라우저에서 실시간으로 재생하는 데 성공했어요. 이번 공연은 영국 싱어송라이터 에이미 메이의 곡 \'Open\'으로, 에미상 후보에 오른 감독 에드 프레이만이 연출했어요. WebGPU 기술로 초당 17~75Mbps 대역폭에서 스트리밍되며 재생 길이 제한이 없고, 데스크톱·모바일·Meta Quest 3 헤드셋에서 모두 재생 가능해요. 공개 첫 주말에만 여러 플랫폼을 합산해 150만 뷰를 기록했어요.</p><p>기존 볼류메트릭 캡처는 폴리곤 메시 방식으로 기하학적 정확도는 높지만 피부 질감이나 미세 디테일에서 어색함이 있었어요. DNE의 독자 카메라 그리드 스테이지와 Gracia의 4DGS 처리 파이프라인을 결합하면 재구성 방식이 메시에서 레디언스 필드로 전환돼, 부드러운 경계면·피하 산란·미세 디테일을 훨씬 사실적으로 표현할 수 있어요. 폴리곤보다 피부와 머리카락 같은 유기적 소재를 더 자연스럽게 구현하는 것이 핵심 강점이에요.</p><p>4DGS가 게임 시네마틱과 버추얼 프로덕션 파이프라인으로 빠르게 이동할 가능성이 높아, 아티스트와 게임 개발자 모두 주목할 기술로 떠오르고 있어요. 앱 설치 없이 웹에서 바로 재생되는 스트리밍 방식은 관객 접근성을 크게 높이며 인터랙티브 라이브 콘텐츠의 새로운 가능성을 열어요.</p><p>원문: <a href="https://www.cgchannel.com/2026/04/dne-and-gracia-release-4-minute-streamable-4dgs-performance/">CG Channel</a></p>',
            source:      'CG Channel',
            publishedAt: '2026.04.28',
            hue:         270,
            url:         'https://www.cgchannel.com/2026/04/dne-and-gracia-release-4-minute-streamable-4dgs-performance/',
            urls: [
                { label: '영상', href: 'https://gracia.com' },
            ],
        },
        {
            id:          'art-dff8143d-2026-04',
            tab:         'art',
            headline:    '웹툰 엔터테인먼트, Genies와 파트너십으로 웹툰 캐릭터를 AI 3D 아바타로 확장',
            summary:     '웹툰 엔터테인먼트가 AI 아바타 기업 Genies와 손잡고 웹툰 캐릭터를 인터랙티브 3D 포맷으로 확장하는 팬 경험 서비스를 발표했어요.',
            body:        '<p>웹툰 엔터테인먼트가 AI 아바타 기업 Genies와 파트너십을 체결하고, 웹툰 캐릭터를 인터랙티브 3D 포맷으로 확장하는 새로운 팬 경험 서비스를 2026년 4월 27일 발표했어요. 첫 참여 작품은 \'가장 위대한 부동산 개발자\', \'기사는 오늘도 살아남는다\' 등 6개 작품으로, 팬들은 올여름부터 좋아하는 캐릭터와 채팅하고, 작가가 개발한 숨겨진 설정을 잠금 해제하며, 수집형 디지털 아이템을 획득할 수 있어요. Genies는 앞서 산리오와 파트너십을 맺은 AI 아바타 기업으로, 이번에도 크리에이터가 직접 아바타 제작에 참여해 자신의 아트 스타일이 반영되도록 하는 방식을 채택했어요.</p><p>이번 협업에서 가장 눈에 띄는 점은 \'크리에이터 퍼스트\' 정책이에요. 크리에이터의 동의 없이는 어떤 에셋도 제작하지 않고, AI가 작가의 고유한 아트 스타일을 반영하도록 작가가 직접 과정에 참여해요. 웹툰 엔터테인먼트 대표 김용수는 \'크리에이터가 우리 웹툰의 모든 것의 토대\'라며, 이 파트너십이 작품 세계를 페이지 너머로 확장하는 새로운 방법이 될 것이라고 밝혔어요. Genies CEO 아카시 니감은 팬들이 사랑하는 캐릭터를 인터랙티브 디지털 경험으로 전환하는 크리에이터 지원 툴 개발에 기대감을 표했어요.</p><p>기존 AI 캐릭터화 논란과 달리 크리에이터 동의와 스타일 반영을 전제로 한 구조여서, AI 도입에 비판적인 웹툰 창작 커뮤니티에서도 차별화된 접근으로 주목받고 있어요. 수집형 디지털 아이템 연동까지 더해져 팬덤 경제와 IP 확장의 새로운 모델이 될지 주목돼요.</p><p>원문: <a href="https://variety.com/2026/gaming/news/webtoon-entertainment-genies-ai-1236729996/">Variety</a></p>',
            source:      'Variety',
            publishedAt: '2026.04.28',
            hue:         280,
            image:       'https://variety.com/wp-content/uploads/2026/04/Webtoon_Header-1.png?crop=0px%2C0px%2C4800px%2C2700px&resize=1000%2C563',
            url:         'https://variety.com/2026/gaming/news/webtoon-entertainment-genies-ai-1236729996/',
        },
        {
            id:          'art-39dfc68f-2026-04',
            tab:         'art',
            headline:    '캔바 어피니티 3.2, 클로드 데스크톱 AI 자동화 기능 탑재',
            summary:     '캔바가 어피니티 3.2를 출시해 클로드 데스크톱 AI 연동으로 창작 작업 자동화를 베타 도입했다. 사진·벡터·레이아웃 통합 앱에 자연어 명령 자동화가 더해졌다.',
            body:        '<p>디자인 작업을 하다 보면 반복 작업에 지쳐 자동화를 꿈꾸게 되죠. 어피니티 3.2가 드디어 그 꿈을 현실로 만들어 드립니다! 포토, 디자이너, 퍼블리셔를 하나로 합친 이 무료 크리에이티브 앱에 클로드 AI 자동화가 탑재됐어요.</p><p>캔바는 2026년 4월 27일 어피니티 3.2를 공개했다. 이번 업데이트의 핵심 기능은 앤스로픽의 클로드 데스크톱(Claude Desktop) 연동이다. 사용자는 자연어로 명령을 입력해 어피니티 앱 내의 반복 작업을 자동화할 수 있으며, 해당 AI 커넥터 기능은 현재 무료 베타로 제공 중이다. 캔바 유료 구독자라면 어피니티 내에서 캔바의 다양한 AI 창작 도구도 함께 활용할 수 있다.</p><p>어피니티는 원래 어피니티 포토(사진 편집), 어피니티 디자이너(벡터 그래픽), 어피니티 퍼블리셔(페이지 레이아웃)의 세 가지 독립 앱으로 구성됐으나, 캔바에 인수된 뒤 하나의 플랫폼으로 통합됐다. 현재 핵심 앱은 무료 계정으로 이용 가능하다. 3.2 업데이트에서는 중간 톤 디테일을 강화하는 텍스처 필터, 새로운 벡터 블롭·이레이즈 브러시, 다빈치 리졸브 실시간 동기화, 캡처원 내보내기 지원 등 다양한 기능이 추가됐다.</p><p>클로드 커넥터는 베타 기간 동안 무료이지만, 캔바 AI 도구를 추가 활용하려면 캔바 프로(연간 144달러) 이상의 유료 구독이 필요하다. 이번 업데이트는 Adobe 대항마로 자리매김한 어피니티가 AI 자동화 영역에서도 경쟁력을 강화하려는 시도로 풀이된다. 반복 작업에서 해방된 크리에이터들이 더 창의적인 작업에 집중할 수 있는 환경이 마련되고 있다.</p><p>원문: <a href="https://www.cgchannel.com/2026/04/canva-releases-affinity-3-2/">CG Channel</a></p>',
            source:      'CG Channel',
            publishedAt: '2026.04.27',
            hue:         200,
            image:       'https://www.cgchannel.com/wp-content/uploads/2026/04/260427_Affinity31_f.jpg',
            url:         'https://www.cgchannel.com/2026/04/canva-releases-affinity-3-2/',
        },
        {
            id:          'art-b05348a3-2026-04',
            tab:         'art',
            headline:    '세계 최초 AI 아트 전문 미술관, LA에서 6월 개관',
            summary:     '레픽 아나돌의 \'데이터랜드\'가 6월 20일 LA 다운타운에서 개관을 앞두고 있으며, 생성 AI 예술의 윤리적 가능성을 탐구한다고 밝혔다.',
            body:        '<p>세계 최초의 AI 아트 전문 미술관 \'데이터랜드(Dataland)\'가 오는 6월 20일 LA 다운타운에 문을 연다!</p><p>터키계 미국인 아티스트 레픽 아나돌이 공동 설립한 이 미술관은 프랭크 게리가 설계한 \'더 그랜드 LA\' 복합단지 내 3만 5,000 제곱피트 공간에 5개의 몰입형 갤러리를 갖추고 있다.</p><p>단순한 AI 생성 이미지를 넘어 \'책임감 있는 AI 예술\'이란 무엇인지를 묻는 실험적 공간이어서 주목된다.</p><p>개관 첫 전시는 아나돌의 \'머신 드림스: 레인포레스트(Machine Dreams: Rainforest)\'로, 전 세계 16개 열대우림에서 직접 수집한 수백만 건의 자연 이미지와 사운드를 기반으로 만든 거대 언어 모델(LNM)을 활용한 몰입형 시청각 설치 작품이다. 스미소니언, 코넬 조류연구소, 게티 등 권위 있는 기관들과의 데이터 파트너십도 맺었다.</p><p>미술관은 지속 가능성에도 집중했다. 오리건주 구글 클라우드 서버를 활용해 87% 탄소 제로 재생에너지로 운영되며, 방문객 한 명이 경험 전체에 사용하는 전력은 스마트폰 충전 한 번에 해당하는 수준이라고 아나돌은 설명했다. AI 아트에 대한 저작권·편향성 논란이 이어지는 가운데, 데이터랜드는 허가 기반 데이터셋과 완전한 투명성을 통해 새로운 기준을 제시하겠다고 강조했다.</p><p>원문: <a href="https://www.npr.org/2026/04/25/nx-s1-5799511/dataland-refik-anadol-los-angeles-ai-art-museum">NPR</a></p>',
            source:      'NPR',
            publishedAt: '2026.04.26',
            hue:         270,
            image:       'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/11656x8742+0+0/resize/1100/quality/50/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fa6%2F13%2F20c3e7b74ac9a20ecb24e002dcdc%2Fgallery-c-infinity-room-9.jpg',
            url:         'https://www.npr.org/2026/04/25/nx-s1-5799511/dataland-refik-anadol-los-angeles-ai-art-museum',
            urls: [
                { label: '공식 사이트', href: 'https://dataland.art/' },
            ],
        },
        {
            id:          'art-50937f7b-2026-04',
            tab:         'art',
            headline:    '오픈소스 AI 창작 도구 ComfyUI, 5억 달러 가치로 3천만 달러 조달',
            summary:     '생성 AI 출력물을 노드 방식으로 세밀하게 제어하는 ComfyUI가 시리즈 B로 3천만 달러를 유치하며 5억 달러 기업 가치를 인정받았다.',
            body:        '<p>크리에이터들이 AI 이미지·영상·오디오를 정밀하게 제어할 수 있게 해주는 ComfyUI가 시리즈 B 투자로 3천만 달러를 조달하며 5억 달러 기업 가치를 인정받았다!</p><p>이번 라운드는 Craft Ventures가 주도했고, Pace Capital·Chemistry·TruArrow 등이 참여했다. ComfyUI는 2023년 오픈소스 프로젝트로 시작해 2024년 말 시리즈 A로 1,900만 달러를 조달한 데 이어 이번에도 빠른 성장을 보여줬다.</p><p>미드저니나 ChatGPT 같은 단일 프롬프트 기반 툴이 60~80% 정도의 완성도에 그치는 반면, ComfyUI의 노드 기반 인터페이스는 생성 과정의 각 단계를 분리해 원하는 요소만 수정할 수 있어 \'AI 슬롭\' 넘쳐나는 시대에 특히 주목받고 있다.</p><p>현재 400만 명 이상의 사용자를 보유한 ComfyUI는 VFX, 애니메이션, 광고, 산업 디자인 등 다양한 전문 분야에서 쓰이고 있으며, 스튜디오 구인 공고에 \'ComfyUI 아티스트·엔지니어\'라는 직함이 등장할 만큼 크리에이티브 산업의 핵심 도구로 자리 잡았다. CEO 요란 옌은 "AI 슬롭이 범람하는 세상에서 인간 개입 방식의 ComfyUI 접근법이 결국 주목받게 될 것"이라고 강조했다.</p><p>원문: <a href="https://techcrunch.com/2026/04/24/comfyui-hits-500m-valuation-as-creators-seek-more-control-over-ai-generated-media/">TechCrunch</a></p>',
            source:      'TechCrunch',
            publishedAt: '2026.04.26',
            hue:         210,
            image:       'https://techcrunch.com/wp-content/uploads/2026/04/ComfyUI-Co-founders-1.png?w=1024',
            url:         'https://techcrunch.com/2026/04/24/comfyui-hits-500m-valuation-as-creators-seek-more-control-over-ai-generated-media/',
            urls: [
                { label: '공식 사이트', href: 'https://www.comfy.org/' },
            ],
        },
        {
            id: 'openai-chatgpt-images-2-followup-0427',
            tab: 'art',
            headline: "OpenAI, 차세대 이미지 생성기 'ChatGPT Images 2.0' — '르네상스'라 자칭",
            summary: "CEO 샘 알트만이 'AI 이미지 르네상스'라 칭한 ChatGPT Images 2.0의 씽킹 모드와 만화·잡지 레이아웃 자동 생성 기능을 살펴봐요.",
            body: '<p>OpenAI가 4월 21일 ChatGPT Images 2.0을 발표했어요 — CEO 샘 알트만은 이를 AI 이미지 생성의 \'르네상스\'라고 표현했어요.<br/>인스턴트 모드와 씽킹(Thinking) 모드 두 가지가 있으며, 씽킹 모드는 웹 검색·다중 이미지 생성·자동 오류 검토를 지원하고, 만화 페이지나 잡지 레이아웃 같은 복잡한 작업도 한 번에 처리해요.<br/>텍스트 렌더링과 다국어 지원이 크게 향상되어 광고·일러스트·만화 등 크리에이티브 작업에 폭넓게 쓸 수 있을 것 같아서, 디지털 아티스트들이 주목할 만한 업데이트예요!</p><p>원문: <a href="https://gizmodo.com/openai-unveils-new-image-generator-to-usher-in-an-ai-slop-renaissance-2000749159">Gizmodo</a></p>',
            source: 'Gizmodo',
            publishedAt: '2026.04.27',
            hue: 290,
            image: 'https://gizmodo.com/app/uploads/2026/04/SamAltman_surfing_like_zuck_AI-generated-1200x675.jpg',
            url: 'https://gizmodo.com/openai-unveils-new-image-generator-to-usher-in-an-ai-slop-renaissance-2000749159',
        },
        {
            id: 'twelvelabs-nab-2026-0427',
            tab: 'art',
            headline: "TwelveLabs, NAB 2026에서 영상 인텔리전스 신제품 'Pegasus 1.5'·'Rodeo' 공개",
            summary: 'TwelveLabs가 타임스탬프 메타데이터 추출 모델 Pegasus 1.5와 자연어 영상 편집 도구 Rodeo를 NAB Show 2026에서 선보였어요.',
            body: '<p>TwelveLabs가 NAB Show 2026(4월 20일)에서 새 영상 이해 모델 Pegasus 1.5와 크리에이터용 AI 편집 도구 Rodeo를 발표했어요.<br/>Pegasus 1.5는 단 한 번의 API 호출로 영상 전체에 타임스탬프가 달린 구조화 메타데이터를 추출하며, Gemini 2.5 Pro 대비 세그먼테이션 품질이 30% 앞서요. Rodeo는 자연어로 영상을 검색·편집·조합할 수 있는 AI 공동 제작 도구예요.<br/>방송·스포츠·기업 영상팀이 수작업 태깅과 편집에 쏟던 시간을 대폭 줄일 수 있어서, 영상 중심 크리에이티브 산업의 워크플로우가 크게 바뀔 것 같아요!</p><p>원문: <a href="https://www.prweb.com/releases/twelvelabs-unveils-the-next-era-of-video-intelligence-at-nab-show-2026-302746715.html">PRWeb</a></p>',
            source: 'PRWeb',
            publishedAt: '2026.04.27',
            hue: 290,
            image: 'https://mma.prnewswire.com/media/2959740/NEWTLLOGO.jpg?p=facebook',
            url: 'https://www.prweb.com/releases/twelvelabs-unveils-the-next-era-of-video-intelligence-at-nab-show-2026-302746715.html',
            urls: [
              { label: '바로가기', href: 'https://www.twelvelabs.io/' },
            ],
        },
        {
            id: 'openai-sora-app-shutdown-day-0426',
            tab: 'art',
            headline: 'OpenAI Sora 앱, 오늘부로 공식 종료 — AI 버블의 조용한 경고',
            summary: '하루 100만 달러 추론 비용, 이용자 반토막, 디즈니+ 파트너십 취소를 끝으로 Sora 앱이 4/26 공식 서비스를 종료했어요.',
            body: '<p>OpenAI의 AI 동영상 생성 앱 Sora의 앱·웹 서비스가 오늘(4월 26일) 공식 종료됐어요.<br/>Sora는 하루 약 100만 달러의 추론 비용을 부담하면서도 출시 후 이용자가 100만 명에서 50만 명 이하로 급감했고, 디즈니+와의 10억 달러 파트너십도 함께 취소됐어요.<br/>AI 비디오 생성이 얼마나 비용 집약적인지를 보여준 사례로, Runway·Pika Labs 등 경쟁 서비스들이 반사 이익을 누릴지 귀추가 주목돼요.</p><p>원문: <a href="https://www.creativebloq.com/ai/ai-art/what-does-openais-sora-shutdown-mean-for-the-future-of-ai-video">Creative Bloq</a></p>',
            source: 'Creative Bloq',
            publishedAt: '2026.04.26',
            hue: 290,
            image: 'https://cdn.mos.cms.futurecdn.net/VT57Xpu5ho3w3P7JT7dV3V-1000-80.jpg',
            url: 'https://www.creativebloq.com/ai/ai-art/what-does-openais-sora-shutdown-mean-for-the-future-of-ai-video',
            urls: [
              { label: '공식 FAQ', href: 'https://help.openai.com/en/articles/20001152-what-to-know-about-the-sora-discontinuation' },
            ],
        },
        {
            id: 'kling-3-native-4k-video-0425',
            tab: 'art',
            headline: 'Kling 3.0, 업스케일링 없는 네이티브 4K AI 영상 생성 출시',
            summary: 'Kuaishou의 Kling 3.0이 업계 최초 네이티브 4K 텍스트-투-비디오와 최대 6컷 멀티샷 시퀀스를 지원해요.',
            body: '<p>Kuaishou의 AI 영상 생성 모델 Kling이 4월 24일 버전 3.0을 출시하며 업계 최초 네이티브 4K 텍스트-투-비디오를 선보였어요.<br/>업스케일링이나 후처리 없이 단일 텍스트 프롬프트 한 번으로 제작 즉시 사용 가능한 4K 영상이 뽑히고, 최대 6컷 멀티샷 시퀀스와 오디오 동기화 생성도 지원돼요.<br/>마케터·광고 대행사·인디 필름메이커가 스튜디오급 영상을 추가 편집 없이 바로 얻을 수 있게 됐다는 점에서, 영상 제작 비용과 시간이 획기적으로 줄어들 전망이에요!</p><p>원문: <a href="https://www.vo3ai.com/blog/kling-30-just-launched-native-4k-video3-ways-it-changes-ai-filmmaking-2026-04-24">VO3 AI Blog</a></p>',
            source: 'VO3 AI Blog',
            publishedAt: '2026.04.25',
            hue: 290,
            image: 'https://pub-40fc341bb75049a4af5e73bf5afac3ba.r2.dev/blog-images/blog-cover-1777028586188.jpg',
            url: 'https://www.vo3ai.com/blog/kling-30-just-launched-native-4k-video3-ways-it-changes-ai-filmmaking-2026-04-24',
            urls: [
              { label: 'Kling AI 바로가기', href: 'https://klingai.com/global/' },
            ],
        },
        {
            id: 'openai-sora-shutdown-notice-0425',
            tab: 'art',
            headline: 'OpenAI Sora, 내일(4/26) 앱 서비스 종료… 전략 전환의 신호탄',
            summary: 'OpenAI가 Sora 앱·웹 서비스를 4/26 종료하며 컴퓨팅 자원을 기업용 제품에 집중한다고 밝혔어요. API는 9월 24일까지 유지돼요.',
            body: '<p>OpenAI가 텍스트-투-비디오 서비스 Sora를 4월 26일부로 앱 및 웹 서비스를 종료한다고 밝혔어요 (API는 9월 24일 종료 예정).<br/>사용자들은 Sora 라이브러리에서 영상·이미지를 지금 당장 내보내야 하며, 종료 후에는 계정 데이터가 영구 삭제돼요. OpenAI는 코딩 도구·엔터프라이즈 제품 쪽 컴퓨팅 자원 확보를 위해 Sora를 종료하는 것으로 알려졌어요.<br/>불과 1년 사이에 월간 활성 이용자가 절반 이하로 줄었다는 점에서, 소비자 대상 AI 크리에이티브 도구 시장이 얼마나 치열한지 실감하게 되네요.</p><p>원문: <a href="https://the-decoder.com/openai-sets-two-stage-sora-shutdown-with-app-closing-april-2026-and-api-following-in-september/">The Decoder</a></p>',
            source: 'The Decoder',
            publishedAt: '2026.04.25',
            hue: 290,
            image: 'https://the-decoder.com/wp-content/uploads/2024/09/openai_sora_screens-2.png',
            url: 'https://the-decoder.com/openai-sets-two-stage-sora-shutdown-with-app-closing-april-2026-and-api-following-in-september/',
            urls: [
              { label: 'OpenAI 공식 안내', href: 'https://help.openai.com/en/articles/20001152-what-to-know-about-the-sora-discontinuation' },
            ],
        },
        {
            id: 'adobe-firefly-ai-assistant-0425',
            tab: 'art',
            headline: "Adobe, Creative Cloud 전체를 지휘하는 AI 에이전트 'Firefly AI Assistant' 발표",
            summary: 'Adobe가 Photoshop·Premiere·Lightroom 등 CC 앱 전체에서 멀티스텝 워크플로를 대화형으로 실행하는 Firefly AI Assistant를 공개했어요.',
            body: '<p>Adobe가 Photoshop·Premiere·Lightroom 등 Creative Cloud 앱 전체에 걸쳐 복잡한 멀티스텝 워크플로를 대화형으로 실행하는 \'Firefly AI Assistant\'를 공개했어요.<br/>\'세련된 포트레이트 리터칭\' 같은 사전 설정 Creative Skills는 물론, 사용자가 자신만의 스킬을 직접 만들 수 있고, Kling 3.0·Luma AI·ElevenLabs 등 30개 이상 외부 AI 모델도 단일 인터페이스에서 쓸 수 있어요.<br/>Adobe가 단순 생성 도구를 넘어 크리에이티브 전체 파이프라인을 통합하는 오케스트레이터로 진화하려는 야심이 느껴지는 발표예요!</p><p>원문: <a href="https://blog.adobe.com/en/publish/2026/04/15/introducing-firefly-ai-assistant-new-way-create-with-our-creative-agent">Adobe Blog</a></p>',
            source: 'Adobe Blog',
            publishedAt: '2026.04.25',
            hue: 290,
            url: 'https://blog.adobe.com/en/publish/2026/04/15/introducing-firefly-ai-assistant-new-way-create-with-our-creative-agent',
            urls: [
              { label: 'BusinessWire 원문', href: 'https://www.businesswire.com/news/home/20260415853653/en/Adobe-Ushers-in-a-New-Era-of-Creativity-with-New-Creative-Agent-and-Generative-AI-Innovations-in-Adobe-Firefly' },
            ],
        },
        {
            id: 'elevenlabs-eleven-music-ios-0425',
            tab: 'art',
            headline: "ElevenLabs, AI 음악 생성 앱 'ElevenMusic' iOS 출시",
            summary: '보이스 AI 기업 ElevenLabs가 저작권 라이선스 기반으로 텍스트 프롬프트 음악 생성과 리믹스를 지원하는 iOS 앱 ElevenMusic을 출시했어요.',
            body: '<p>보이스 AI 기업 ElevenLabs가 텍스트 프롬프트로 음악을 만들고 다른 사람의 곡을 리믹스할 수 있는 iOS 앱 ElevenMusic을 출시했어요.<br/>하루 7곡 무료 생성, 월 9.99달러 Pro 구독 시 500곡까지 생성 가능하며, 앱 내 라이브 스테이션·Top Charts 등 스트리밍 기능도 갖췄어요. 학습 데이터는 저작권 문제를 피하기 위해 처음부터 Merlin Network·Kobalt Music Group과 라이선스 계약을 맺었어요.<br/>AI 음악 시장에서 Suno·Udio와 정면 경쟁에 나선 ElevenLabs, 저작권 안전성을 앞세운 전략이 크리에이터들한테 어떻게 먹힐지 기대되네요!</p><p>원문: <a href="https://techcrunch.com/2026/04/02/elevenlabs-releases-a-new-ai-powered-music-generation-app/">TechCrunch</a></p>',
            source: 'TechCrunch',
            publishedAt: '2026.04.25',
            hue: 290,
            image: 'https://techcrunch.com/wp-content/uploads/2025/01/ElevenLabs-feat.jpg?resize=1200,669',
            url: 'https://techcrunch.com/2026/04/02/elevenlabs-releases-a-new-ai-powered-music-generation-app/',
        },
        {
            id: 'starti-ai-studio-2-0424',
            tab: 'art',
            headline: 'Starti AI Studio 2.0 출시 — 광고 영상 생성에서 완전한 크리에이티브 루프 시스템으로',
            summary: 'Starti.ai가 생성·배포·분석·최적화를 하나로 잇는 완결형 AI 광고 영상 제작 시스템 AI Studio 2.0을 출시했어요.',
            body: '<p>AI 광고 영상 제작 플랫폼 Starti.ai가 생성·배포·분석·최적화를 하나로 잇는 완결형 시스템 AI Studio 2.0을 4월 24일 공식 출시했어요.<br/>이번 업그레이드의 핵심은 디렉터 수준의 사고로 숏 플래닝부터 후반 작업까지 처리하는 Video Agent, 동적 콘텐츠 인식 기반의 Motion Graphics, 그리고 Google·Meta 데이터를 연동해 영상 구조 단위로 성과를 분석하는 Smart Insight 모듈이에요.<br/>단순 영상 클립 생성을 넘어 브랜드 일관성을 자동 유지하면서 캠페인 성과까지 역추적할 수 있는 시스템이라, 콘텐츠 마케팅과 광고 제작 현장에 실질적인 변화를 가져올 것으로 기대돼요!</p><p>원문: <a href="https://www.manilatimes.net/2026/04/24/tmt-newswire/pr-newswire/starti-ai-studio-upgrades-to-20-from-video-generation-tool-to-complete-advertising-creative-system/2327490">PR Newswire</a></p>',
            source: 'PR Newswire',
            publishedAt: '2026.04.24',
            hue: 290,
            url: 'https://www.manilatimes.net/2026/04/24/tmt-newswire/pr-newswire/starti-ai-studio-upgrades-to-20-from-video-generation-tool-to-complete-advertising-creative-system/2327490',
            urls: [
              { label: '공식 사이트', href: 'https://www.starti.ai' },
            ],
        },
        {
            id: 'weekly-genai-roundup-0424',
            tab: 'art',
            headline: '[4/17~23 주간 생성 AI 뉴스] 이미지 \'사고\' 시대 개막·디자인 AI 등장·리서치 에이전트 전면 가동',
            summary: '4월 17~23일 한 주 동안 ChatGPT Images 2.0, Claude 업데이트, Google Deep Research Max 등 실용 단계 AI 도구가 대거 등장했어요.',
            body: '<p>지난 한 주(4월 17~23일) 생성 AI 분야에서는 ChatGPT Images 2.0 출시를 기점으로 이미지 생성이 실무 도구 수준으로 올라섰다는 평가가 나왔어요.<br/>OpenAI의 이미지 \'사고(thinking)\' 기능으로 텍스트 렌더링 정확도가 크게 개선됐고, Anthropic의 Claude Opus 4.7 업데이트와 Google의 Deep Research Max(MCP 연동) 출시도 주요 소식으로 꼽혔죠.<br/>이미지·디자인·리서치 에이전트 세 영역이 동시에 실용 단계로 진입하면서, 크리에이터와 게임 아티스트가 당장 써볼 수 있는 AI 도구 선택지가 이번 주에만 확 넓어졌어요!</p><p>원문: <a href="https://blog.greeden.me/en/2026/04/23/april-17-april-23-2026-weekly-generative-ai-news-roundup-the-practical-rise-of-image-thinking-the-emergence-of-design-ai-and-the-full-scale-arrival-of-research-agents/">IT &amp; Life Hacks Blog</a></p>',
            source: 'IT & Life Hacks Blog',
            publishedAt: '2026.04.24',
            hue: 290,
            image: 'https://blog.greeden.me/wp-content/uploads/2025/02/pexels-photo-373543.jpeg',
            url: 'https://blog.greeden.me/en/2026/04/23/april-17-april-23-2026-weekly-generative-ai-news-roundup-the-practical-rise-of-image-thinking-the-emergence-of-design-ai-and-the-full-scale-arrival-of-research-agents/',
        },
        {
            id: 'openai-chatgpt-images-2-launch-0423',
            tab: 'art',
            headline: 'OpenAI, ChatGPT 이미지 2.0 출시 — 텍스트 렌더링 혁신, 이미지 아레나 1위 달성',
            summary: 'OpenAI의 ChatGPT Images 2.0이 출시 12시간 만에 Image Arena 전 카테고리 1위에 올랐어요. 다국어 텍스처 렌더링과 최대 10장 동시 생성이 핵심이에요.',
            body: '<p>OpenAI가 4월 21일 ChatGPT Images 2.0을 출시했어요. 출시 12시간 만에 Image Arena 전 카테고리에서 1위를 차지했대요!<br/>한국어·중국어 등 다국어 텍스트 렌더링이 대폭 개선됐고, 최대 2,000px 해상도에 다양한 가로세로 비율 지원, 1회 프롬프트로 이미지 최대 10장 생성 기능도 들어갔어요.<br/>텍스트가 들어간 UI, 인포그래픽, 만화·게임 아트에서 획기적인 품질 향상이 이뤄졌기 때문에 디지털 아티스트와 게임 개발자에게 특히 주목받고 있어요.</p><p>원문: <a href="https://siliconangle.com/2026/04/21/openai-launches-chatgpt-images-2-0-codex-labs-developer-training-service/">SiliconANGLE</a></p>',
            source: 'SiliconANGLE',
            publishedAt: '2026.04.23',
            hue: 290,
            image: 'https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2026/04/ChatGPT.png',
            url: 'https://siliconangle.com/2026/04/21/openai-launches-chatgpt-images-2-0-codex-labs-developer-training-service/',
            urls: [
              { label: '공식 페이지', href: 'https://openai.com/chatgpt/overview/' },
            ],
        },
        {
            id: 'grai-ai-music-seed-0423',
            tab: 'art',
            headline: 'AI 뮤직 스타트업 GRAI, 900만 달러 시드 투자 유치 — 음악을 소셜 경험으로',
            summary: 'GRAI가 Khosla Ventures 주도로 900만 달러 시드 투자를 유치, 기존 트랙 리믹스와 소셜 공유에 집중한 AI 음악 플랫폼을 선보여요.',
            body: '<p>AI 음악 스타트업 GRAI가 Khosla Ventures 주도로 900만 달러 시드 투자를 유치했어요. 빔린스키 창업자들이 핀터레스트에 동영상 앱을 매각한 뒤 새로 도전한 프로젝트예요.<br/>Suno·Udio처럼 곡을 처음부터 만들어 주는 게 아니라, 기존 트랙을 리믹스하고 친구들과 공유할 수 있는 소셜 음악 경험에 초점을 맞췄어요. 아티스트 동의 기반 운영 원칙도 강조해요.<br/>생성 AI 음악 툴들이 대부분 창작 자체에 집중하는 것과 달리 GRAI는 소비·공유·발견 측면에 집중한다는 점에서 음악 AI 시장에 새로운 방향을 제시해요!</p><p>원문: <a href="https://techcrunch.com/2026/04/21/grai-believes-ai-can-make-music-more-social-not-replace-artists/">TechCrunch</a></p>',
            source: 'TechCrunch',
            publishedAt: '2026.04.23',
            hue: 290,
            url: 'https://techcrunch.com/2026/04/21/grai-believes-ai-can-make-music-more-social-not-replace-artists/',
        },
        {
            id: 'lightcraft-spark-nab-2026-0423',
            tab: 'art',
            headline: 'Lightcraft Spark, NAB Show 2026 최고 혁신상 수상 — AI 기반 브라우저 영화 사전제작 플랫폼',
            summary: 'AI·3D·영화 제작 워크플로를 브라우저에서 하나로 합친 Lightcraft Spark가 NAB Show 2026 최고 혁신상을 수상했어요.',
            body: '<p>Lightcraft의 Spark 플랫폼이 NAB Show 2026(4월 18~22일)에서 최고 혁신상(Greatest Innovation)을 수상했어요!<br/>Spark는 브라우저에서 AI, 3D 툴, 영화 제작 워크플로를 하나로 합쳐 팀이 실시간으로 씬을 만들고 샷을 블로킹하며 사전 시각화를 할 수 있게 해줘요. Maya, Blender, UE5 등 기존 3D 앱과도 연동돼요.<br/>영화·광고·게임 트레일러 프리프로덕션을 수개월에서 몇 시간으로 단축할 수 있다는 점에서 콘텐츠 제작 파이프라인 전반을 바꿀 잠재력을 인정받은 거예요!</p><p>원문: <a href="https://www.provideocoalition.com/best-in-show-awards-at-nab-2026/">ProVideo Coalition</a></p>',
            source: 'ProVideo Coalition',
            publishedAt: '2026.04.23',
            hue: 290,
            url: 'https://www.provideocoalition.com/best-in-show-awards-at-nab-2026/',
            urls: [
              { label: '공식 소개', href: 'https://lightcraft.pro/coverage/lightcraft-spark-ai-assisted-filmmaking-platform/' },
            ],
        }
  ],
};
