/* AI Art Daily — site config (탭 정의) */
/* 기사 데이터는 data/index.json + data/articles/YYYY-MM-DD.json 에 날짜별로 나뉘어 있다. */
window.AIAD = {
  tabs: [
    { id: 'games', label: '게임 제작 속 AI', desc: '게임 아트 리소스 제작에 사용되는 AI 관련 뉴스들을 매일 업데이트합니다.' },
    { id: 'industry', label: 'AI 도입 뉴스', desc: '게임 스튜디오들의 AI 도입과 관련된 뉴스들을 매일 업데이트합니다.' },
    { id: 'art', label: '아트 전반 AI 뉴스', desc: '게임 제작과 무관하게 모든 아트 관련 AI 뉴스들을 매일 업데이트합니다.' },
  ],

  // 로그인 (Supabase + Google). 두 값이 비어 있으면 로그인 버튼이 보이지 않는다.
  // supabaseAnonKey는 브라우저에 공개되도록 만든 키(anon / publishable)라 여기 둬도 된다.
  // service_role(secret) 키는 절대 넣지 않는다.
  auth: {
    supabaseUrl: '',        // 예: 'https://abcdefghijkl.supabase.co'
    supabaseAnonKey: '',
  },

  // 아티스트 브리핑 — 게임 아트 직군마다 관심 가질 뉴스·업데이트를 골라 보여 준다 (주소: /for/<id>/)
  // short:    헤더 '내 직군' 표시·추천 표시에 쓰는 짧은 이름
  // photo:    (선택) 메인 브리핑 머리 띠 배경 사진 — 3:1, 사람은 오른쪽, 왼쪽은 어둡게 비운 사진. 없으면 icons/roles/<id>.svg 일러스트
  // tags:     기사 서브 카테고리(data/keywords.json) 중 이 직군과 바로 이어지는 것
  // terms:    기사 제목·요약·본문, 업데이트 제목·요약·세부 내용에서 찾을 단어 (영문은 단어 단위, 한글은 띄어쓰기 무시)
  // services: 이 직군이 쓰는 업데이트 서비스 (slug) — 그 서비스의 업데이트는 모두 추천
  // 고르는 기준 (app.jsx roleMatch, scripts/build_site.py role_match가 같아야 한다):
  //   기사 — 서브 카테고리 3점, 제목의 단어 3점, 요약의 단어 2점, 본문에만 있는 단어 1점. 3점 이상만
  //   업데이트 — services에 든 서비스, 또는 제목·요약·세부 내용에 단어가 있는 것
  roles: [
    { id: '3d', label: '3D 아티스트', short: '3D', desc: '모델링·텍스처·머티리얼과 3D 생성 AI', photo: '/icons/roles/3d.webp',
      tags: ['3D', '텍스처', '가우시안 스플래팅', 'Blender', 'Meshy', 'Tripo', 'Autodesk'],
      terms: ['3D 모델', '3D 에셋', '3D 생성', '모델링', '텍스처', '리토폴로지', '토폴로지', 'UV', 'PBR', '머티리얼',
              '스컬프팅', '메시', '폴리곤', 'image-to-3D', 'text-to-3D', 'Blender', '블렌더', 'Maya', 'ZBrush', 'Substance',
              '3ds Max', 'Houdini', 'Hunyuan3D', 'TRELLIS', 'Meshy', 'Tripo', 'Rodin'],
      services: ['meshy', 'tripo', 'rodin', 'blender', 'roblox-cube'] },
    { id: '2d', label: '2D·컨셉 아티스트', short: '2D·컨셉', desc: '일러스트·컨셉아트·이미지 생성과 편집',
      tags: ['2D·이미지', 'Photoshop', 'Midjourney'],
      terms: ['일러스트', '컨셉 아트', '컨셉아트', '이미지 생성', '이미지 편집', '캐릭터 디자인', '드로잉', '페인팅', '스케치',
              '인페인팅', '업스케일', '스타일 참조', 'LoRA', 'Photoshop', '포토샵', 'Procreate', 'Clip Studio', 'Midjourney',
              'Firefly', 'Krita', '스프라이트', '픽셀 아트', '웹툰'],
      services: ['midjourney', 'gpt-image', 'nano-banana', 'seedream', 'qwen-image', 'flux', 'stable-diffusion', 'krea',
                 'recraft', 'magnific', 'gigapixel', 'mai-image', 'firefly', 'scenario', 'layer', 'invokeai'] },
    { id: 'animator', label: '애니메이터', short: '애니메이터', desc: '캐릭터 애니메이션·모션 캡처·립싱크',
      tags: ['애니메이션'],
      terms: ['애니메이터', '캐릭터 애니메이션', '3D 애니메이션', '모션 캡처', '모캡', 'mocap', 'motion capture', '키프레임',
              '인비트윈', '중간 프레임', '립싱크', 'lip sync', 'lip-sync', '페이셜', '표정 애니메이션', '동작 생성', 'text-to-motion',
              'Cascadeur', 'Mixamo', 'Rokoko', 'iClone', 'Move AI', 'Wonder Studio', 'Wonder Dynamics', 'Flow Studio'],
      services: ['rokoko', 'iclone', 'flow-studio', 'hedra'] },
    { id: 'rigger', label: '리거', short: '리거', desc: '리깅·스키닝·페이셜 리그 자동화',
      tags: [],
      terms: ['리깅', '리거', '오토 리깅', '자동 리깅', 'rig', 'rigging', 'auto-rig', 'auto rig', 'AccuRIG', '스키닝', 'skinning',
              '웨이트 페인팅', '블렌드셰이프', 'blendshape', 'blend shape', '스켈레톤', 'skeleton', '페이셜 리그', 'ARKit',
              'Mixamo', 'Cascadeur'],
      services: ['rokoko', 'iclone'] },
    { id: 'vfx', label: 'VFX 아티스트', short: 'VFX', desc: '이펙트·합성·시뮬레이션과 영상 생성 AI',
      tags: ['VFX'],
      terms: ['VFX', '시각 효과', '시각효과', '이펙트', '파티클', '컴포지팅', 'compositing', '로토스코핑', 'rotoscoping', 'Nuke',
              'Houdini', 'After Effects', 'Niagara', '시뮬레이션', '유체', '그린 스크린', 'green screen', '매치무브', '리라이팅',
              'relight', 'Wonder Studio', 'Runway', 'DaVinci', '영상 생성', 'video generation'],
      services: ['runway', 'veo', 'kling', 'seedance', 'wan', 'dream-machine', 'ltx-studio', 'pika', 'topaz-video', 'higgsfield'] },
    { id: 'ta', label: '테크니컬 아티스트', short: 'TA', desc: '파이프라인·셰이더·엔진·도구 자동화',
      tags: ['MCP', 'Unreal Engine', 'Unity', 'DLSS', '코딩'],
      terms: ['테크니컬 아티스트', '셰이더', 'shader', '파이프라인', 'pipeline', '프로시저럴', 'procedural', 'PCG', 'Houdini',
              'Python', '파이썬', '스크립트', '플러그인', 'MCP', 'ComfyUI', 'Unreal Engine', '언리얼', 'Unity', '유니티',
              'Godot', 'LOD', '실시간 렌더링', 'DLSS', 'USD', 'OpenUSD', 'SDK'],
      services: ['comfyui', 'invokeai', 'unity-ai', 'nvidia-studio', 'hugging-face', 'fal.ai', 'blender', 'claude'] },
    { id: 'env', label: '레벨 아티스트', short: '레벨', desc: '월드·지형·스플래팅과 배경 생성',
      tags: ['가우시안 스플래팅'],
      terms: ['월드 모델', 'world model', '3D 월드', '월드 생성', '레벨 디자인', '지형', 'terrain', '오픈 월드', '배경 아트',
              '환경 아트', '가우시안 스플래팅', 'Gaussian Splatting', '포토그래메트리', 'photogrammetry', '스카이박스', 'skybox',
              '파노라마', 'HDRI', 'Genie', 'World Labs', 'Marble', 'PCG'],
      services: ['marble'] },
    { id: 'sound', label: '사운드 디자이너', short: '사운드', desc: '효과음·음악·음성·더빙 AI',
      tags: ['음악·사운드', '음성', 'ElevenLabs', 'Suno'],
      terms: ['사운드', '효과음', '음향', '작곡', 'BGM', '배경음악', '보이스', '음성 합성', '성우', 'TTS', 'text-to-speech',
              '더빙', 'dubbing', '오디오', 'audio', 'sound effect', 'SFX', 'ElevenLabs', 'Suno', 'Udio', 'Stable Audio',
              'MusicGen', 'Lyria', 'Wwise', 'FMOD'],
      services: ['elevenlabs', 'suno', 'mureka', 'stable-audio', 'minimax-audio'] },
    { id: 'ui', label: 'UI·UX 디자이너', short: 'UI·UX', desc: '인터페이스·아이콘·벡터·타이포',
      tags: [],
      terms: ['UI 디자인', 'UI·UX', 'UI/UX', '게임 UI', 'UX', '인터페이스 디자인', '아이콘', 'icon', '로고', '타이포', '폰트', 'font',
              '벡터 그래픽', '벡터 변환', 'vector graphics', 'SVG', '와이어프레임', 'Figma', '피그마', '디자인 시스템', 'HUD'],
      services: ['figma-ai', 'recraft'] },
  ],

  // 사이드바 대분류 '업데이트' — 공식 업데이트를 모아 볼 아트 관련 AI 서비스(제품) (분류 순서 = 필터 순서)
  // name:   사이드바에 보이는 제품(서비스) 이름 / maker: 만든 회사 (제품 이름과 같으면 생략)
  // url:    방문자에게 보여 줄 공식 업데이트 페이지
  // notice: 공지 수집에 읽을 곳 — 제품 공지·변경 기록·블로그 (RSS가 있으면 RSS)
  // dev:    개발자(API) 변경 기록 — 서비스에 있으면 반드시 넣는다
  // match:  위 출처가 회사의 여러 제품을 섞어 내면, 이 제품 글로 볼 단어 (하나라도 들어간 글만). 비어 있으면 출처의 글 전부
  // 여러 분야 제품을 내는 회사는 제품마다 해당 분야에 따로 넣는다.
  // 주소 확인: python3 scripts/check_update_sources.py
  updateSources: [
    { category: '이미지', name: 'Midjourney', url: 'https://updates.midjourney.com/',
      notice: ['https://updates.midjourney.com/rss/'],
      dev: [],
      match: [] },
    { category: '이미지', name: 'GPT Image', maker: 'OpenAI', url: 'https://openai.com/news/',
      notice: ['https://openai.com/news/rss.xml'],
      dev: ['https://developers.openai.com/api/docs/changelog'],
      match: ['gpt-image', 'ChatGPT Images', 'image generation'] },
    { category: '이미지', name: 'Nano Banana', maker: 'Google', url: 'https://deepmind.google/models/gemini-image/',
      notice: ['https://deepmind.google/blog/rss.xml', 'https://blog.google/products/gemini/rss/', 'https://gemini.google/release-notes/'],
      dev: ['https://ai.google.dev/gemini-api/docs/changelog', 'https://docs.cloud.google.com/feeds/gemini-enterprise-agent-platform-release-notes.xml', 'https://docs.cloud.google.com/gemini-enterprise-agent-platform/release-notes'],
      match: ['Nano Banana', 'Gemini Image', 'flash-image', 'pro-image'] },
    { category: '이미지', name: 'Seedream', maker: 'ByteDance', url: 'https://seed.bytedance.com/en/blog',
      notice: ['https://seed.bytedance.com/sitemap.xml'],
      dev: ['https://docs.byteplus.com/en/docs/ModelArk/1159178'],
      match: ['Seedream'] },
    { category: '이미지', name: 'Qwen-Image', maker: 'Alibaba', url: 'https://qwen.ai/blog',
      notice: [],
      dev: ['https://www.alibabacloud.com/help/en/model-studio/newly-released-models'],
      match: ['qwen-image'] },
    { category: '이미지', name: 'FLUX', maker: 'Black Forest Labs', url: 'https://bfl.ai/blog',
      notice: ['https://bfl.ai/blog'],
      dev: ['https://docs.bfl.ai/release-notes/rss.xml', 'https://docs.bfl.ai/release-notes'],
      match: [] },
    { category: '이미지', name: 'Stable Diffusion', maker: 'Stability AI', url: 'https://stability.ai/news-updates',
      notice: ['https://stability.ai/news-updates?format=rss'],
      dev: ['https://platform.stability.ai/docs/release-notes'],
      match: ['Stable Diffusion', 'Stable Image'] },
    { category: '이미지', name: 'Krea', url: 'https://www.krea.ai/docs/changelog',
      notice: ['https://www.krea.ai/docs/changelog/rss.xml'],
      dev: ['https://www.krea.ai/docs/changelog'],
      match: [] },
    { category: '이미지', name: 'Recraft', url: 'https://www.recraft.ai/blog',
      notice: ['https://www.recraft.ai/blog', 'https://www.recraft.ai/news'],
      dev: [],
      match: [] },
    { category: '이미지', name: 'Magnific', maker: 'Freepik', url: 'https://www.magnific.com/blog',
      notice: [],
      dev: ['https://docs.magnific.com/changelog'],
      match: [] },
    { category: '이미지', name: 'Gigapixel', maker: 'Topaz Labs', url: 'https://www.topazlabs.com/gigapixel',
      notice: ['https://community.topazlabs.com/c/topaz-gigapixel/topaz-gigapixel-releases/128.rss', 'https://www.topazlabs.com/news'],
      dev: ['https://community.topazlabs.com/c/api/api-releases/136.rss', 'https://community.topazlabs.com/c/api/api-releases/136'],
      match: ['Gigapixel'] },
    { category: '이미지', name: 'MAI-Image', maker: 'Microsoft AI', url: 'https://microsoft.ai/news/',
      notice: ['https://techcommunity.microsoft.com/t5/s/gxcuf89792/rss/board?board.id=Azure-AI-Foundry-Blog'],
      dev: ['https://learn.microsoft.com/en-us/azure/foundry/whats-new-foundry'],
      match: ['MAI-Image'] },
    { category: '영상', name: 'Veo', maker: 'Google', url: 'https://deepmind.google/models/veo/',
      notice: ['https://deepmind.google/blog/rss.xml', 'https://blog.google/technology/google-labs/rss/'],
      dev: ['https://ai.google.dev/gemini-api/docs/changelog'],
      match: ['Veo', 'Flow'] },
    { category: '영상', name: 'Kling', maker: 'Kuaishou', url: 'https://kling.ai/blog',
      notice: ['https://kling.ai/blog', 'https://app.klingai.com/global/release-notes'],
      dev: ['https://kling.ai/document-api/updates/api'],
      match: [] },
    { category: '영상', name: 'Seedance', maker: 'ByteDance', url: 'https://seed.bytedance.com/en/blog',
      notice: ['https://seed.bytedance.com/sitemap.xml'],
      dev: ['https://docs.byteplus.com/en/docs/ModelArk/1159178'],
      match: ['Seedance'] },
    { category: '영상', name: 'Wan', maker: 'Alibaba', url: 'https://www.alibabacloud.com/help/en/model-studio/newly-released-models',
      notice: [],
      dev: ['https://www.alibabacloud.com/help/en/model-studio/newly-released-models'],
      match: ['wan'] },
    { category: '영상', name: 'Grok Imagine', maker: 'xAI', url: 'https://x.ai/news',
      notice: [],
      dev: ['https://docs.x.ai/developers/release-notes'],
      match: ['Imagine', 'image generation', 'video generation', 'grok-imagine', 'grok-2-image'] },
    { category: '영상', name: 'Runway', url: 'https://runwayml.com/changelog',
      notice: ['https://runwayml.com/changelog', 'https://runwayml.com/news'],
      dev: ['https://docs.dev.runwayml.com/api-details/api_changelog/'],
      match: [] },
    { category: '영상', name: 'Dream Machine', maker: 'Luma AI', url: 'https://lumalabs.ai/news',
      notice: ['https://lumalabs.ai/news'],
      dev: ['https://docs.lumalabs.ai/changelog.rss', 'https://docs.lumalabs.ai/changelog'],
      match: [] },
    { category: '영상', name: 'Higgsfield', url: 'https://higgsfield.ai/blog',
      notice: ['https://higgsfield.ai/blog/rss.xml'],
      dev: [],
      match: [] },
    { category: '영상', name: 'LTX Studio', maker: 'Lightricks', url: 'https://ltx.studio/blog-category/product-updates',
      notice: ['https://ltx.studio/blog-category/product-updates'],
      dev: ['https://huggingface.co/api/models?author=Lightricks&sort=lastModified&direction=-1&limit=5', 'https://huggingface.co/Lightricks'],
      match: [] },
    { category: '영상', name: 'Pika', url: 'https://pika.art/blog',
      notice: ['https://pika.art/blog'],
      dev: [],
      match: [] },
    { category: '영상', name: 'Hailuo', maker: 'MiniMax', url: 'https://www.minimax.io/blog',
      notice: ['https://www.minimax.io/blog'],
      dev: ['https://platform.minimax.io/docs/release-notes/models.md', 'https://platform.minimax.io/docs/release-notes/apis'],
      match: ['Hailuo', 'video'] },
    { category: '영상', name: 'PixVerse', url: 'https://pixverse.ai/en/blog',
      notice: ['https://pixverse.ai/en/blog'],
      dev: ['https://docs.platform.pixverse.ai/change-logs-906383m0'],
      match: [] },
    { category: '영상', name: 'Hedra', url: 'https://www.hedra.com/blog',
      notice: ['https://www.hedra.com/blog/feed.xml'],
      dev: [],
      match: [] },
    { category: '영상', name: 'HeyGen', url: 'https://www.heygen.com/blog/heygen-release-update-tracking',
      notice: ['https://heygen.noticeable.news/feed.rss'],
      dev: ['https://docs.heygen.com/changelog/rss.xml', 'https://docs.heygen.com/changelog'],
      match: [] },
    { category: '영상', name: 'Synthesia', url: 'https://www.synthesia.io/updates',
      notice: ['https://www.synthesia.io/updates'],
      dev: ['https://docs.synthesia.io/changelog.rss', 'https://docs.synthesia.io/changelog'],
      match: [] },
    { category: '영상', name: 'Topaz Video', maker: 'Topaz Labs', url: 'https://www.topazlabs.com/topaz-video',
      notice: ['https://community.topazlabs.com/c/topaz-video/topaz-video-releases/122.rss', 'https://www.topazlabs.com/news'],
      dev: ['https://community.topazlabs.com/c/api/api-releases/136.rss', 'https://community.topazlabs.com/c/api/api-releases/136'],
      match: ['Topaz Video'] },
    { category: '3D', name: 'Meshy', url: 'https://www.meshy.ai/blog',
      notice: ['https://www.meshy.ai/blog'],
      dev: ['https://docs.meshy.ai/en/api/changelog'],
      match: [] },
    { category: '3D', name: 'Tripo', maker: 'VAST', url: 'https://www.tripo3d.ai/blog',
      notice: [],
      dev: ['https://docs.tripo3d.ai/get-started/changelog.html'],
      match: [] },
    { category: '3D', name: 'Rodin', maker: 'Hyper3D', url: 'https://hyper3d.ai/blog',
      notice: ['https://hyper3d.ai/blog'],
      dev: ['https://docs.hyper3d.ai/en/get-started/changelog'],
      match: [] },
    { category: '3D', name: 'Marble', maker: 'World Labs', url: 'https://www.worldlabs.ai/blog',
      notice: ['https://www.worldlabs.ai/blog'],
      dev: ['https://docs.worldlabs.ai/marble/release-notes'],
      match: [] },
    { category: '게임 에셋', name: 'Scenario', url: 'https://www.scenario.com/changelog',
      notice: ['https://www.scenario.com/changelog', 'https://www.scenario.com/blog'],
      dev: ['https://www.scenario.com/changelog'],
      match: [] },
    { category: '게임 에셋', name: 'Layer', maker: 'Layer AI', url: 'https://www.layer.ai/changelog',
      notice: ['https://www.layer.ai/changelog', 'https://www.layer.ai/blog'],
      dev: [],
      match: [] },
    { category: '게임 에셋', name: 'Ludo.ai', url: 'https://ludo.ai/whats-new',
      notice: ['https://ludo.ai/whats-new', 'https://ludo.ai/blog'],
      dev: [],
      match: [] },
    { category: '게임 에셋', name: 'Roblox Cube', maker: 'Roblox', url: 'https://devforum.roblox.com/c/updates/announcements/36',
      notice: ['https://devforum.roblox.com/c/updates/announcements/36.rss'],
      dev: ['https://devforum.roblox.com/c/updates/release-notes/62.rss', 'https://create.roblox.com/docs/release-notes'],
      match: ['Cube', 'Assistant', 'AI', 'Texture Generation', 'Segment Any Mesh'] },
    { category: '모션', name: 'Rokoko', url: 'https://www.rokoko.com/insights',
      notice: ['https://www.rokoko.com/insights'],
      dev: ['https://support.rokoko.com/api/v2/help_center/en-us/sections/4414320656401/articles.json', 'https://support.rokoko.com/hc/en-us/sections/4414320656401-Rokoko-Studio-Release-Notes'],
      match: [] },
    { category: '모션', name: 'iClone', maker: 'Reallusion', url: 'https://www.reallusion.com/iclone/update.html',
      notice: ['https://magazine.reallusion.com/feed/', 'https://www.reallusion.com/iclone/update.html'],
      dev: [],
      match: ['iClone'] },
    { category: '모션', name: 'Flow Studio', maker: 'Autodesk', url: 'https://help.wonderdynamics.com/release-notes/',
      notice: ['https://help.wonderdynamics.com/release-notes/'],
      dev: [],
      match: [] },
    { category: '음악·음성', name: 'ElevenLabs', url: 'https://elevenlabs.io/docs/changelog',
      notice: ['https://elevenlabs.io/blog'],
      dev: ['https://elevenlabs.io/docs/changelog.rss', 'https://elevenlabs.io/docs/changelog'],
      match: [] },
    { category: '음악·음성', name: 'Suno', url: 'https://suno.com/release-notes',
      notice: ['https://suno.com/release-notes', 'https://suno.com/blog'],
      dev: [],
      match: [] },
    { category: '음악·음성', name: 'Mureka', maker: 'Kunlun Tech', url: 'https://www.mureka.ai/whats-new_en.html',
      notice: ['https://www.mureka.ai/whats-new_en.html'],
      dev: ['https://platform.mureka.ai/docs/en/changelog.html'],
      match: [] },
    { category: '음악·음성', name: 'Stable Audio', maker: 'Stability AI', url: 'https://stability.ai/stable-audio',
      notice: ['https://stability.ai/news-updates?format=rss'],
      dev: ['https://platform.stability.ai/docs/release-notes'],
      match: ['Stable Audio'] },
    { category: '음악·음성', name: 'MiniMax Audio', maker: 'MiniMax', url: 'https://www.minimax.io/audio',
      notice: ['https://www.minimax.io/blog'],
      dev: ['https://platform.minimax.io/docs/release-notes/models.md', 'https://platform.minimax.io/docs/release-notes/apis'],
      match: ['Speech', 'Music', 'Audio', 'Voice'] },
    { category: '도구', name: 'Firefly', maker: 'Adobe', url: 'https://helpx.adobe.com/firefly/web/whats-new/new-features/whats-new.html',
      notice: ['https://community.adobe.com/announcements-402', 'https://blog.adobe.com/en/topics/adobe-firefly'],
      dev: ['https://developer.adobe.com/firefly-services/docs/firefly-api/getting-started/changelog/'],
      match: ['Firefly'] },
    { category: '도구', name: 'ComfyUI', url: 'https://docs.comfy.org/changelog',
      notice: ['https://docs.comfy.org/changelog/rss.xml', 'https://blog.comfy.org/feed'],
      dev: ['https://github.com/Comfy-Org/ComfyUI/releases.atom', 'https://github.com/Comfy-Org/ComfyUI/releases'],
      match: [] },
    { category: '도구', name: 'InvokeAI', maker: 'Invoke', url: 'https://invoke.ai/releases/',
      notice: ['https://invoke.ai/releases/'],
      dev: ['https://github.com/invoke-ai/InvokeAI/releases.atom', 'https://github.com/invoke-ai/InvokeAI/releases'],
      match: [] },
    { category: '도구', name: 'Unity AI', maker: 'Unity', url: 'https://unity.com/blog',
      notice: ['https://unity.com/blog/rss'],
      dev: ['https://packages.unity.com/com.unity.ai.assistant'],
      match: ['Unity AI', 'AI Assistant', 'Generators', 'agent', 'MCP'] },
    { category: '도구', name: 'NVIDIA Studio', maker: 'NVIDIA', url: 'https://blogs.nvidia.com/blog/tag/rtx-ai-garage/',
      notice: ['https://blogs.nvidia.com/blog/tag/rtx-ai-garage/feed/', 'https://blogs.nvidia.com/blog/tag/nvidia-studio/feed/'],
      dev: [],
      match: [] },
    { category: '도구', name: 'Hugging Face', url: 'https://huggingface.co/changelog',
      notice: ['https://huggingface.co/changelog', 'https://huggingface.co/blog/feed.xml'],
      dev: [],
      match: [] },
    { category: '도구', name: 'fal.ai', url: 'https://docs.fal.ai/changelog',
      notice: ['https://blog.fal.ai/rss/'],
      dev: ['https://docs.fal.ai/changelog/rss.xml', 'https://docs.fal.ai/changelog'],
      match: [] },
    { category: '도구', name: 'Figma AI', maker: 'Figma', url: 'https://www.figma.com/release-notes/',
      notice: ['https://www.figma.com/release-notes/feed/atom.xml'],
      dev: ['https://developers.figma.com/docs/rest-api/changelog/'],
      match: ['AI', 'Make', 'Weave', 'agent', 'generative'] },
    { category: '도구', name: 'Blender', url: 'https://www.blender.org/news/',
      notice: ['https://www.blender.org/feed/'],
      dev: ['https://code.blender.org/feed/', 'https://developer.blender.org/docs/release_notes/'],
      match: [] },
    { category: '도구', name: 'Claude', maker: 'Anthropic', url: 'https://www.anthropic.com/news',
      notice: ['https://www.anthropic.com/news', 'https://support.claude.com/en/articles/12138966-release-notes'],
      dev: ['https://platform.claude.com/docs/en/release-notes/overview'],
      match: ['Claude'] },
  ],

  /*
   * 날짜 파일(data/articles/*.json)의 기사 형식:
   * {
   *   id:          'unique-slug',          // any unique string
   *   tab:         'games',                // must match a tab id above
   *   headline:    '한국어 제목',
   *   summary:     '한 줄 요약',
   *   body:        '<p>본문 첫 문단</p><p>두 번째 문단…</p>',  // 카드 클릭 시 모달 본문 (HTML 허용)
   *   source:      '출처',
   *   publishedAt: '2026.04.25',           // 'YYYY.MM.DD' 형식, 사이트 업로드 날짜 (정렬·날짜 헤더에 사용; 화면에는 그대로 표시됨)
   *   hue:         30,                     // 0–360, 그라디언트 썸네일 색상
   *   image:       'assets/news/x.jpg',    // optional — 있으면 그라디언트 대신 이미지 사용
   *   keywords:    ['3D', 'Blender'],      // 서브 카테고리 — 그 탭의 data/keywords.json 목록에 있는 값만
   *   url:         'https://...',          // 원문 링크
   *   urls: [                              // optional — 추가 관련 링크
   *     { label: '관련 보도', href: 'https://...' },
   *     { label: '공식 발표', href: 'https://...' },
   *   ],
   * }
   */
};
