/* Whitelist — 스크래핑 대상 목록 (단순 데이터 파일) */
window.AIAD_WHITELIST = {
  /* 기사 소스 — 카테고리별 출처 도메인 (중복 제거) */
  articleSources: [
    /* ── 공통 (AI 뉴스레터 / 빅랩 / 일반 기술 매체) ── */
    { name: 'The Rundown AI',        url: 'https://www.therundown.ai',                  note: 'AI 데일리 뉴스레터', group: '공통' },
    { name: "Ben's Bites",           url: 'https://bensbites.com',                      note: 'AI 데일리 뉴스레터', group: '공통' },
    { name: 'The Neuron Daily',      url: 'https://www.theneurondaily.com',             note: 'AI 데일리 뉴스레터', group: '공통' },
    { name: 'MarkTechPost',          url: 'https://www.marktechpost.com',               note: 'AI · 머신러닝 기술 매체', group: '공통' },
    { name: 'Creative Bloq',         url: 'https://www.creativebloq.com',               note: '디자인 · 크리에이티브', group: '공통' },
    { name: 'OpenAI News',           url: 'https://openai.com/news',                    note: 'OpenAI 공식 발표', group: '공통' },
    { name: 'OpenAI Developers Blog',url: 'https://developers.openai.com/blog',         note: 'OpenAI 개발자 블로그', group: '공통' },
    { name: 'DeepMind Blog',         url: 'https://deepmind.google/blog',               note: 'Google DeepMind 리서치', group: '공통' },
    { name: 'Google AI Blog',        url: 'https://blog.google/technology/ai',          note: 'Google AI 발표', group: '공통' },
    { name: 'Runway Research',       url: 'https://runwayml.com/research',              note: 'Runway 리서치', group: '공통' },
    { name: 'Hugging Face Blog',     url: 'https://huggingface.co/blog',                note: '오픈소스 AI 허브', group: '공통' },
    { name: 'Towards Data Science',  url: 'https://towardsdatascience.com',             note: '데이터 사이언스 · ML', group: '공통' },
    { name: 'The Verge',             url: 'https://www.theverge.com',                   note: '테크 · 컬처 매체', group: '공통' },

    /* ── 게임 제작 (엔진 · 3D · 생성형 툴 · VFX) ── */
    { name: 'Game Developer',        url: 'https://www.gamedeveloper.com',              note: '게임 개발 전문 매체', group: '게임 제작 속 AI' },
    { name: 'Unreal Engine Blog',    url: 'https://www.unrealengine.com/blog',          note: 'Unreal Engine 공식', group: '게임 제작 속 AI' },
    { name: 'Unity Blog',            url: 'https://unity.com/blog',                     note: 'Unity 공식', group: '게임 제작 속 AI' },
    { name: 'VentureBeat — Games',   url: 'https://venturebeat.com/games',              note: '게임 · 비즈니스', group: '게임 제작 속 AI' },
    { name: 'NVIDIA Blog',           url: 'https://blogs.nvidia.com',                   note: 'GPU · AI 인프라', group: '게임 제작 속 AI' },
    { name: 'Stability AI News',     url: 'https://stability.ai/news-updates',          note: 'Stability AI 공식', group: '게임 제작 속 AI' },
    { name: 'Runway Blog',           url: 'https://runwayml.com/blog',                  note: '비디오 생성 AI', group: '게임 제작 속 AI' },
    { name: 'Adobe Business — AI',   url: 'https://business.adobe.com/ai.html',         note: 'Adobe 엔터프라이즈 AI', group: '게임 제작 속 AI' },
    { name: 'Midjourney',            url: 'https://www.midjourney.com',                 note: '이미지 생성 AI', group: '게임 제작 속 AI' },
    { name: 'Meshy Blog',            url: 'https://www.meshy.ai/blog',                  note: '3D 에셋 생성 AI', group: '게임 제작 속 AI' },
    { name: 'Luma Labs',             url: 'https://lumalabs.ai',                        note: '3D · 비디오 생성 AI', group: '게임 제작 속 AI' },
    { name: 'ElevenLabs Blog',       url: 'https://elevenlabs.io/blog',                 note: '음성 생성 AI', group: '게임 제작 속 AI' },
    { name: 'CG Channel',            url: 'https://www.cgchannel.com',                  note: 'VFX · 3D 그래픽스', group: '게임 제작 속 AI' },
    { name: 'fxguide',               url: 'https://www.fxguide.com',                    note: 'VFX 전문 매체', group: '게임 제작 속 AI' },
    { name: 'befores & afters',      url: 'https://beforesandafters.com',               note: 'VFX · 애니메이션', group: '게임 제작 속 AI' },
    { name: 'SideFX News',           url: 'https://www.sidefx.com/news',                note: 'Houdini 공식', group: '게임 제작 속 AI' },
    { name: 'Autodesk Blogs',        url: 'https://www.autodesk.com/blogs',             note: 'Maya · 3ds Max · AI', group: '게임 제작 속 AI' },
    { name: 'TechCrunch',            url: 'https://techcrunch.com',                     note: '테크 · 스타트업', group: '게임 제작 속 AI' },
    { name: 'Ars Technica',          url: 'https://arstechnica.com',                    note: '테크 · 사이언스', group: '게임 제작 속 AI' },
    { name: 'WIRED',                 url: 'https://www.wired.com',                      note: '테크 · 컬처', group: '게임 제작 속 AI' },
    { name: 'Papers with Code',      url: 'https://paperswithcode.com',                 note: '논문 · 구현체 큐레이션', group: '게임 제작 속 AI' },

    /* ── 글로벌 스튜디오 AI 도입 (게임 산업 · 비즈니스) ── */
    { name: 'GDC',                   url: 'https://gdconf.com/news-insights/',          note: 'Game Developers Conference', group: 'AI 도입 뉴스' },
    { name: 'GamesIndustry.biz',     url: 'https://www.gamesindustry.biz',              note: '게임 산업 비즈니스', group: 'AI 도입 뉴스' },
    { name: 'PocketGamer.biz',       url: 'https://www.pocketgamer.biz',                note: '모바일 게임 비즈니스', group: 'AI 도입 뉴스' },
    { name: 'Kotaku',                url: 'https://kotaku.com',                         note: '게임 컬처 매체', group: 'AI 도입 뉴스' },
    { name: 'Polygon',               url: 'https://www.polygon.com',                    note: '게임 · 엔터테인먼트', group: 'AI 도입 뉴스' },
    { name: 'IGN',                   url: 'https://www.ign.com',                        note: '게임 미디어', group: 'AI 도입 뉴스' },
    { name: 'Eurogamer',             url: 'https://www.eurogamer.net',                  note: '유럽 게임 매체', group: 'AI 도입 뉴스' },
    { name: 'Rock Paper Shotgun',    url: 'https://www.rockpapershotgun.com',           note: 'PC 게임 매체', group: 'AI 도입 뉴스' },
    { name: 'PC Gamer',              url: 'https://www.pcgamer.com',                    note: 'PC 게임 매체', group: 'AI 도입 뉴스' },
    { name: 'GamesRadar',            url: 'https://www.gamesradar.com',                 note: '게임 미디어', group: 'AI 도입 뉴스' },
    { name: 'Bloomberg',             url: 'https://www.bloomberg.com',                  note: '비즈니스 · 산업', group: 'AI 도입 뉴스' },
    { name: 'Reuters',               url: 'https://www.reuters.com',                    note: '글로벌 통신사', group: 'AI 도입 뉴스' },

    /* ── 아트 전반 (음악 · 영상 · 사운드 · 리서치) ── */
    { name: 'VentureBeat — AI',      url: 'https://venturebeat.com/ai',                 note: 'AI 산업 동향', group: '아트 전반 AI 뉴스' },
    { name: 'Adobe Research',        url: 'https://research.adobe.com',                 note: 'Adobe 리서치', group: '아트 전반 AI 뉴스' },
    { name: 'Suno Blog',             url: 'https://suno.ai/blog',                       note: '음악 생성 AI', group: '아트 전반 AI 뉴스' },
    { name: 'MusicTech',             url: 'https://musictech.com',                      note: '음악 제작 매체', group: '아트 전반 AI 뉴스' },
    { name: 'Sound on Sound',        url: 'https://www.soundonsound.com',               note: '음악 · 사운드 엔지니어링', group: '아트 전반 AI 뉴스' },
    { name: 'No Film School',        url: 'https://nofilmschool.com',                   note: '영상 제작', group: '아트 전반 AI 뉴스' },
    { name: 'The Next Web',          url: 'https://thenextweb.com',                     note: '테크 · 컬처', group: '아트 전반 AI 뉴스' },
  ],
};
